### ISSUE TITLE
Manifest, Data segment 저장 경로

### ISSUE THREAD

**Issue by tribela** [uni2u/difs#1]
현재 Data segment들을 스토리지 루트에 `hash("name/segment")` 형태로 저장하고 있습니다.
Manifest를 생성할 경우 이를 따로 저장하는 것이 좋을 지, 아니면 구분하지 않고 그냥 통합해서 저장할지 정하는 것이 좋을 듯 합니다.

## 나눌 경우:
* repo_root
  * data (실제 데이터)
    * hash1
    * hash2
  * manifests
    * manifest_hash2
    * manifest_hash2

## 나누지 않을 경우:
* repo_root
  * hash(data/segment01)
  * hash(data/segment02)
  * hash(manifest/hash01)
  * hash(manifest/hash02)

## 비교

| | pro | con |
|:--:|:-- |:-- |
| 나눌 경우 | 디렉터리 구조가 보기 좋음, 관리적인 측면에서 효과적 | FS 스토리지에 저장할 때 name을 파싱하는 과정이 추가되어 성능 저하 |
| 나누지 않을 경우 | 디렉터리 구조 단순화, 성능 저하 없음 | 관리하기 복잡 |

추가적으로 현재 데이터 세그먼트의 해시(uint64_t)와 매니페스트 해시(sha1::hex)가 포맷이 다르다는 문제점이 있습니다.

**Comment by uni2u** [comment]
### 스케치

> manifest file 은 사용자 요청에 대한 첫번째 데이터 파일임
> user interest 에 대한 첫번째 데이터 패킷은 manifest
> request: .../kt.com/아기상어.mp4
> response: manifest file (segment #_00)

#### File Storage
- Data Segment 가 저장되는 장소
  - Data Segment 패킷 단위로 저장
  - if) .../kt.com/아기상어.mp4/#_01
- Data Segment 저장 완료후 manifest 생성 (info manifest)
  - 해당 콘텐츠에 대한 interest 의 첫번째 패킷으로 활용
  - 콘텐츠 이름으로 생성
  - request 예) .../kt.com/아기상어.mp4
  - response 예) manifest file (../kt.com/아기상어.mp4/#_00)
- 생성된 info manifest 는 KV Storage 를 편하게 하기 위함
  - 사용자에게 제공하기 위함은 아님
    - 사용자는 segment 번호를 포함한 interest 를 전송 (KV Storage 의 manifest 에서 start, end 확인)
    - 즉, 사용자는 segment 단위의 interest 를 전송하며 그 시작은 #_01 부터
  - KV Storage 에서 발생한 요청의 응답

```json
{
  "info": {
    "name": "content_name",
    "hash": "hash_value",
    "version_info": "integer"
  },
  "storages": [
    {
      "storage_name": "storage prefix",
      "segment": {
        "start_num": "integer",
        "end_num": "integer"
      }
    }
  ]
}
```

#### KV Storage
- Data (콘텐츠) name 을 해싱한 결과에 해당하는 범위를 책임지는 장소
  - 콘텐츠 이름으로 생성
  - if) .../kt.com/아기상어.mp4
  - name hashing: [.../kt.com/아기상어.mp4] -> hashing
- 같은 이름의 콘텐츠를 제공하는 File Storage 에 대한 manifest 생성
  - 해당 콘텐츠에 대한 interest 의 첫번째 패킷으로 활용
  - File Storage prefix
    - segment num
- KV Storage 의 manifest 는 해당 콘텐츠 이름에 대한 첫번째 패킷으로 제공
  - 사용자는 manifest 의 File Storage 리스트와 세그먼트 정보를 확인하고 직접 interest

``` json
{
  "info": {
    "name": "content_name",
    "hash": "hash_value",
    "version_info": "integer"
  },
  "storages": [
    {
      "storage_name": "storage prefix",
      "segment": {
        "start_num": "integer",
        "end_num": "integer"
      }
    },
    {
      "storage_name": "storage prefix",
      "segment": {
        "start_num": "integer",
        "end_num": "integer"
      }
    }
  ]
}
```

### manifest 저장 경로

- 기본적으로 성능에 대한 이슈가 없어야 함
- 성능 및 관리에 크게 문제되지 않는 경우 통합하는 것을 제안함

**Comment by uni2u** [comment]
- please check comment
- manifest 형식은 File/KV Storage 모두 같음
  - manifest 파일은 하나로 통일
  - manifest 파일은 콘텐츠의 첫번째 데이터 패킷으로 사용됨
    - consumer 의 경우 manifest 를 확인한 뒤 interest 전송
    - consumer 의 경우 콘텐츠를 요청하는 interest 형식은 segment 번호가 포함됨
    - 즉, 콘텐츠의 start 번호를 포함하기 때문에 'segment 번호 00' 을 직접 호출하지 않을 것 
- changed wiki
  - https://github.com/uni2u/difs/wiki/introduce
