### ISSUE TITLE
없는 data_name delete

### ISSUE THREAD

**Issue by uni2u** [uni2u/difs#10]
### [delete]
- `ndndelfile {data_name}`

#### 없는 `data_name` 처리
- ndndelfile: 없는 data_name 을 요청하는 경우
  - DIFS 멈춤현상 발생

- 해결방안
  - warning 메시지 발생
    - exception: `data_name not found`
    - DIFS 시스템이 멈추지 않도록 함

**Comment by tribela** [comment]
Fixed in cee81fc9fdece0e6709ecb617c77ac781a0915fc
