### ISSUE TITLE
batch-chain 적용

### ISSUE THREAD

**Issue by uni2u** [uni2u/difs#14]
### 문제점

- NDN에서 모든 패킷은 signature를 적용하여야 함
- 대용량 데이터의 경우 나뉘어진 패킷의 숫자가 커질 수 있음
- 하나의 데이터를 전송하기 위하여 수많은 signature 가 발생할 수 있음
- signature를 생성하는데 리소스 비용이 많이 발생함
- 또한 verification 에도 많은 리소스 비용이 발생함

### 해소방안

- 최초 패킷에 signature 를 구성하고 다음 패킷의 해시를 가질 수 있도록 함
- 즉, 패킷이 다음 패킷의 해시값을 가지고 있어 다음 패킷을 받으면 이전 패킷의 해시와 비교
- 관련 내용 확인 [2020.07.01. 자료](https://github.com/uni2u/difs/blob/master/meet/20200701-hash_chain.pdf) 참조

#### Batch Chain (Integrity Verifying, Originality)

- Batch (Hash) Chain
  - DIFS 에서 제공하는 Signature 방안으로 'One Signature' 를 통한 데이터 무결성 지원 방안
  - __Batch-Hash__ chain 이라고 naming 함
    - Backward Chain 방식
  - Generation 동작 절차
    - 마지막 패킷 m(메시지): m<sub>end</sub> = name<sub>end</sub> + data<sub>end</sub>
    - 마지막 패킷 k(키): k<sub>end</sub> = Hash(m<sub>end</sub> || null_hash)
    - 첫번째 패킷 k(키): k<sub>1</sub> = Hash(m<sub>1</sub> || k<sub>end</sub>)
    - 첫번째 패킷 RSA_SIGN: RSA_SIGN(Private_Key<sub>cp</sub> || k<sub>1</sub>)
    - 두번째 패킷 k(키): k<sub>2</sub> = Hash(m<sub>2</sub> || k<sub>1</sub>)
    - 세번째 패킷 k(키): k<sub>3</sub> = Hash(m<sub>3</sub> || k<sub>2</sub>)
    - S(세그먼트): S = Encap(Private_Key<sub>cp</sub>, k<sub>1</sub> || k<sub>end</sub>)
  - Verification 동작 절차
    - 첫번째 패킷 받음: k<sub>end</sub> = Decrypt(Public_Key<sub>cp</sub>, S)
    - 받은 패킷: k<sub>1</sub> = Hash(name<sub>1</sub> || data<sub>1</sub> || k<sub>end</sub>)
    - 첫번째 패킷 비교: k<sub>1</sub> == k'<sub>1</sub>
    - 두번째 패킷: k<sub>2</sub> = Hash(name<sub>2</sub> || data<sub>2</sub> || k<sub>1</sub>)
    - 두번째 패킷 비교: k<sub>2</sub> == k'<sub>2</sub>
    - 세번째 패킷: k<sub>3</sub> = Hash(name<sub>3</sub> || data<sub>3</sub> || k<sub>2</sub>)
    - 세번째 패킷 비교: k<sub>3</sub> == k'<sub>3</sub>
    - 마지막 패킷: k<sub>end</sub> = Hash(name<sub>end</sub> || data<sub>end</sub> || null_hash)
    - 마지막 패킷 비교: k<sub>end</sub> == k'<sub>end</sub> (여기서 k<sub>end</sub> 는 첫번째 패킷을 통해 가지고 있음)

```
+-->>[Signature]-----------+  +-->[hash]----------------+  +-->[hash]----------------+     +--------------------+
|  |                       |  |  |                      |  |  |                      |     |                    |
|  | +-------------------+ |  |  | +------------------+ |  |  | +------------------+ |     | +----------------+ |
|  | |hash(#01||#end_key)| ---+  | |hash(#02||#01_key)| ---+  | |hash(#03||#02_key)| |     | |   null hash    | ---+
|  | +-------------------+ |     | +------------------+ |     | +------------------+ |     | +----------------+ |  |
|  | |    data #01       | |     | |    data #02      | |     | |    data #03      | | ... | |    data #END   | |  |
|  | +-------------------+ |     | +------------------+ |     | +------------------+ |     | +----------------+ |  |
|  +-----------------------+     +----------------------+     +----------------------+     +--------------------+  |
|                                                                                                                  |
+----------------------------------------------------------------------------------------------(#end_key)----------+
```

#### Signature Type (blake2b/blake3)

- blake
  - Signature 성능을 높이기 위한 방안으로 'Hash Chain' 과 함께 적용
    - 'sha256' 보다 성능을 대폭 개선한 `blake` 활용
  - 'sha256' 자체의 성능 문제 해소를 위함
    - `blake3` 활용
    - 성능 테스트 결과 `blake2` 가 'sha256' 에 비해 우수함 확인
      - [hash-compare-test](https://github.com/uni2u/difs/blob/master/reference/hash-compare-test%20(7).pdf)
      - [hash-compare-test-rsa](https://github.com/uni2u/difs/blob/master/reference/hash-compare-test-rsa%20(1).pdf)
  - Blake3 적용 관련
    - [Blake3 github](https://github.com/BLAKE3-team/BLAKE3)
      - [Blake3 C base](https://github.com/BLAKE3-team/BLAKE3/tree/master/c)
  - 적용 방안
    - [NDN Packet Format Signature Type](https://named-data.net/doc/NDN-packet-spec/current/signature.html) 추가
    - 개발 우선 순위는 없으나 다음과 같이 구분할 수 있음
      - `SignatureSha256WithHashChain` 추가
      - `DigestBlake3`, `SignatureBlake3WithHashChain` 추가

| Value | Reference | Description |
|:---:|:---|:---|
| 0 | [DigestSha256](https://named-data.net/doc/NDN-packet-spec/current/signature.html#digestsha256) | Integrity protection using SHA-256 digest |
| 1 | [SignatureSha256WithRsa](https://named-data.net/doc/NDN-packet-spec/current/signature.html#signaturesha256withrsa) | Integrity and provenance protection using RSA signature over a SHA-256 digest |
| 3 | [SignatureSha256WithEcdsa](https://named-data.net/doc/NDN-packet-spec/current/signature.html#signaturesha256withecdsa) | Integrity and provenance protection using an ECDSA signature over a SHA-256 digest |
| 4 | [SignatureHmacWithSha256](https://named-data.net/doc/NDN-packet-spec/current/signature.html#signaturehmacwithsha256) | Integrity and provenance protection using SHA256 hash-based message authentication codes |
| 5 `추가` | `SignatureSha256WithHashChain` | Integrity and provenance protection using Hash Chain signature over a SHA-256 digest |
| 6 `추가` | `DigestBlake3` | Integrity protection using Blake3 digest |
| 7 `추가` | `SignatureBlake3WithHashChain` | Integrity and provenance protection using Hash Chain signature over a Blake3 digest |
| 2,5-200 | | reserved for future assignments |
| >200 | `Blake Type 추가` | value 5, 6, 7 |

**Comment by tribela** [comment]
## Hash chain의 문제점
* NDN은 개별 블럭을 가지고 stateless로 사이닝을 함, 다른 블럭의 해시에 의존성을 갖게 되면 별도로 상태를 저장해야 함
  - 다른 세그먼트에 의존하게 되면 성능 저하의 가능성이 있음
  - 무조건 순서대로 처리해야 하는 문제 발생
  - 가장 마지막 블럭을 이용해서 첫번째 블럭을 사이닝 하기 때문에 스트리밍 사용 불가 & 데이터를 끝까지 읽어들이고 마지막 블럭까지 만든 후에야 첫번째 블럭을 사이닝 할 수 있음
* 세그먼트는 그냥 %00부터 지정되는 순차적 넘버링일 뿐임. `/data/1/%41` = `/data/1/A`이기 때문에 세그먼트인지 아닌지 알 방법은 사실상 없음.

**Comment by justin-labry** [comment]
-  NDN은 개별 블럭을 가지고 stateless로 사이닝을 함, 다른 블럭의 해시에 의존성을 갖게 되면 별도로 상태를 저장해야 함
(네, hash chain에 의해서 의존성을 갖게 되는 문제는 이해하고 있습니다)
      - 다른 세그먼트에 의존하게 되면 성능 저하의 가능성이 있음
(네, 이부분에 대해서는 이해하고 있으면 다른 비슷한 스킴 embedded manifest나 hash chain의 실험결과에서 좋은 성능을 보이기 때문에 관련해서 조금 더 알아보고 정보가 있으면 공유하도록 하겠습니다) 
      - 무조건 순서대로 처리해야 하는 문제 발생
(네, 이부분 hash chain 특히 batch hash chain의 특성상 특별한 해결 방법은 없어 보입니다.) 
      - 가장 마지막 블럭을 이용해서 첫번째 블럭을 사이닝 하기 때문에 스트리밍 사용 불가 & 데이터를 끝까지 읽어들이고 마지막 블럭까지 만든 후에야 첫번째 블럭을 사이닝 할 수 있음
(네, 맞습니다. 다만 스트리밍을 위해서 사용할 수 있는 real-time chain이라는 기법을 구상하고 있고 이 방법의 구체적인 내용은 프로젝트의 진행 상황을 고려하여 이야기 하겠습니다.)

**Comment by uni2u** [comment]
#### segments
- `/data/1/A` 로 서비스되는 콘텐츠의 segment 가 %00 밖에 없다면 이에대한 실제 interest 는
  - **/data/1/A/%00**
- `/data/1/A` 로 서비스되는 콘텐츠의 segment 가 5개 존재한다면 이에대한 실제 interest 는
  - **/data/1/A/%00**, **/data/1/A/%01**, **/data/1/A/%02**, **/data/1/A/%03**, **/data/1/A/%04**
- 관련하여 ndn 측에서는 _embedded manifest_ 라고 하는 제안이 있었으며 정보는 다음에서 찾을 수 있습니다.
  - https://named-data.net/publications/techreports/ndn-tr-25-manifest-embedding/
  - https://named-data.net/wp-content/uploads/2014/09/ndn-tr-25-manifest-embedding.pdf

#### segment-fetcher
- 일반적인 경우 ndn-cxx 의 `segment-fetcher` 를 사용하면
- 요청이 왔을 때 해당 데이터의 segment 정보를 반환하는 것으로 알고 있습니다. (세부 확인 필요)
- 관련 정보: https://named-data.net/doc/ndn-cxx/current/doxygen/de/dfc/segment-fetcher_8cpp.html

#### CanBePrefix
- 세그먼트에 대한 interest 는 _CanBePrefix_ 매칭을 통하여 forwarding 하는 것으로 알고 있습니다. (세부 확인 필요)
- https://named-data.net/doc/NDN-packet-spec/current/interest.html

#### DIFS 의 경우
- producer 가 DIFS 에 데이터를 _insert_ 하면서 서비스 할 name 을 지정함 (repo-ng 에서는 이를 _ndn-name_ 이라함, DIFS 에서는 **content-name** 으로 함)
  - producer 는 해당 데이터를 이미 segment 구성을 완료하였으며 각 segment 패킷을 DIFS 에 저장함 
    - producer 의 _insert_ 요청을 받은 노드는 producer 에게 interest 전송
    - producer 는 _segment-fetcher_ 를 통하여 데이터 segment 정보 응답
    - DIFS 는 segment 정보를 확인 후 producer 에게 `/.../%00` 형식의 interest 전송
    - producer 는 데이터(segment) 패킷을 DIFS 에게 응답
    - DIFS 는 데이터(segment) 패킷을 그대로 저장
- consumer 는 **/content-name** 을 알고 있다고 가정함  
- content-name 이 `/data/1/A` 라면 hash 를 통하여 manifest 파일을 얻음
  - manifest 에는 콘텐츠에 대한 정보가 포함됨
- consumer 는 콘텐츠 segment 를 실제 저장하고 있는 DIFS 노드로 _interest_ 전송
  - `/<repo-prefix>/<content-name>/<%segment-num>`
  - **/repo/1/data/A/%00**, **/repo/1/data/A/%01**, **/repo/1/data/A/%02**, ...

**Comment by justin-labry** [comment]
Embedded Manifest 구현의 예제 (manifest.hpp 등등) 
https://github.com/named-data/Consumer-Producer-API

Embedded Manifest Python 구현 예제 
https://github.com/cn-uofbasel/PyCN-lite/blob/master/pycn_lite/lib/flic_enc.py

**Comment by uni2u** [comment]
- batch-chain 은 DIFS 의 성능 (insert/get/delete 등) 을 높이기 위한 내용입니다.
  - NDN 은 signature 를 매 패킷마다 생성하는 것으로 인한 성능 저하를 예상하였기 때문에
  - 단순히 signature 를 줄이면서 verify 까지 만족한다면 성능이 향상될 것이라는 기대를 하는 내용입니다.
    - 다른 것은 깊게 생각해보지 않아서 여기저기 약점이 있을 수 있습니다.

**관련하여 다른 아이디어나 좋은 방법이 있다면 언제든 의견 바랍니다.**

- 성능을 높이기 위한 어떠한 아이디어라도 좋습니다. (언제든 환영입니다. ^^)

**Comment by uni2u** [comment]
@justin-labry 
- [FLIC](https://tools.ietf.org/html/draft-irtf-icnrg-flic-02) 라는 draft 문서가 ICNRG 에서 시작되고 있음
  - File-Link ICN Collection 은 IPFS 팀원도 추가된 것으로 보임

**Comment by uni2u** [comment]
2020.08.21. (금) 회의가 진행되었으며

- hash-chain 은 적용하는 것으로 함
