### ISSUE TITLE
Manifest, Data 이름이 겹치는 문제

### ISSUE THREAD

**Issue by tribela** [uni2u/difs#2]
/repo/1/{insert}/data/1로 데이터를 생성 후 /repo/4/{create}/data/1로 매니페스트를 만들 시 똑같은 `/data/1` 이름을 가진 데이터가 생성 되어 충돌이 발생합니다.
이름이 충돌 나지 않도록 프리픽스를 붙이는 등의 조치가 필요합니다.

**Comment by uni2u** [comment]
### manifest/data Naming 이슈

> manifest file 은 사용자 요청에 대한 첫번째 데이터 파일임
> user interest 에 대한 첫번째 데이터 패킷은 manifest
> request: .../kt.com/아기상어.mp4
> response: manifest file (segment #_00)

#### File Storage
- manifest 의 name 은 실제 content_name 을 의미함
  - 사용자의 interest 에 포함된 network prefix 를 포함한 content_name
    - if) .../kt.com/data/아기상어.mp4
  - content_name 에 해당하는 manifest 생성
    - 해당 콘텐츠에 대한 interest 의 첫번째 패킷으로 활용
    - request 예) .../kt.com/아기상어.mp4
    - response 예) manifest file (../kt.com/아기상어.mp4/#_00)
  - manifest 는 해당 content_name 에 대한 local 검색에 활용됨
    - 사용자는 KV Storage 를 통하여 manifest 를 검색하게 됨
    - 최초 사용자의 request 를 받는 경우 자신이 제공할 수 있는지 확인하여야 함
    - 자신이 제공할 수 있으면 manifest 제공
    - 자신이 제공할 수 없으면 content_name 을 해싱하고 KV Storage 를 찾아 검색
  - File Storage 는 segment 에 대한 데이터 제공
    - 사용자는 segment 번호를 포함한 interest 를 전송 (KV Storage 의 manifest 에서 start, end 확인)
    - 즉, 사용자는 segment 단위의 interest 를 전송하며 그 시작은 #_01 부터
    - request interest: .../kt.com/data/아기상어.mp4/#_01
    - response data: segment (sequence #_00)

```json
{
  "info": {
    "name": "content_name",
    "hash": "hash_value",
    "version_info": "integer"
  },
  "storages": [
    {
      "storage_name": "storage prefix",
      "segment": {
        "start_num": "integer",
        "end_num": "integer"
      }
    }
  ]
}
```

#### KV Storage
- manifest 의 name 은 실제 content_name 을 의미함
  - 사용자의 interest 에 포함된 network prefix 를 포함한 content_name
    - if) .../kt.com/data/아기상어.mp4
    - name hashing: [.../kt.com/data/아기상어.mp4] -> hashing
  - manifest 는 해당 content_name 에 대한 첫번째 데이터 패킷으로 제공됨
    - request interest: .../kt.com/data/아기상어.mp4
    - response data: manifest file

``` json
{
  "info": {
    "name": "content_name",
    "hash": "hash_value",
    "version_info": "integer"
  },
  "storages": [
    {
      "storage_name": "storage prefix",
      "segment": {
        "start_num": "integer",
        "end_num": "integer"
      }
    },
    {
      "storage_name": "storage prefix",
      "segment": {
        "start_num": "integer",
        "end_num": "integer"
      }
    }
  ]
}
```

#### 관리를 위한 naming (Todo)

- 관리를 위한 경우 prefix 구분이 필요함
  - 예를들어 관리자가 자신이 제공하는 콘텐츠들에 대한 manifest 를 확인하고 싶다거나
  - 어떠한 이유로 manifest 파일만 제공받아야 될 경우

**Comment by uni2u** [comment]
- please check comment
- manifest 형식은 File/KV Storage 모두 같음
  - manifest 파일은 하나로 통일
  - manifest 파일은 콘텐츠의 첫번째 데이터 패킷으로 사용됨
    - consumer 의 경우 manifest 를 확인한 뒤 interest 전송
    - consumer 의 경우 콘텐츠를 요청하는 interest 형식은 segment 번호가 포함됨
    - 즉, 콘텐츠의 start 번호를 포함하기 때문에 'segment 번호 00' 을 직접 호출하지 않을 것 
- changed wiki
  - https://github.com/uni2u/difs/wiki/introduce

**Comment by tribela** [comment]
잘 이해가 가지 않는 부분이 몇 가지 있습니다.

> manifest 는 해당 content_name 에 대한 첫번째 데이터 패킷으로 제공됨 

내용물이 `aaaxx`라고 가정하면 manifest와 함께 붙어서 `{"info": …}aaaxx` 이런 식으로 온다고 이해하면 될까요?

> manifest 는 해당 content_name 에 대한 local 검색에 활용됨
    사용자는 KV Storage 를 통하여 manifest 를 검색하게 됨
    최초 사용자의 request 를 받는 경우 자신이 제공할 수 있는지 확인하여야 함
    자신이 제공할 수 있으면 manifest 제공
    자신이 제공할 수 없으면 content_name 을 해싱하고 KV Storage 를 찾아 검색

NDN에서 기본적으로 데이터를 소유하고 있는 곳이 어딘지 몰라고 이름만 제대로 주면 그걸 가지고 있는 누군가가 응답하도록 되어 있는데(repo-ng도 저장 할 때와 삭제 할 때만 repo의 위치를 지정하고 _get_ 을 할 때는 저장소 위치를 필요로 하지 않음) 왜 manifest를 먼저 요구하고 저장소의 위치를 알아야 하는지 이해가 가지 않습니다.
해당 콘텐츠의 청크 갯수나 메타데이터 등을 담는다면 어느 정도 이유가 있어 보이는데 삭제도, 저장도 아닌 get을 할 때 저장소 위치를 알아야 할 필요가 따로 존재하나요?

**Comment by uni2u** [comment]
### basic NDN

- 구매자 요청(interest)에 대하여 데이터로 응답
  - interest: /kt.com/movie/아기상어
  - data: segment01 + segment 정보
- 첫번째 데이터가 전송되면서 몇개의 segment 로 구성되어있는지 정보를 함께 전송
- 구매자의 두번째 요청부터는 segment 번호를 포함한 interest 로 요청
  - interest: /kt.com/movie/아기상어/#_02
  - data: segment 번호에 해당하는 데이터 응답

### DIFS manifest

- basicNDN 의 데이터는 기본적으로 패킷이 가질 수 있는 최대 크기만큼 전송 가능하며
- 패킷 최대 크기를 넘어서는 데이터는 분할하여 제공하는데
- 분할 정보를 consumer 가 알 수 있는 방법이 없음
- DIFS 는 manifest 파일을 사용하여 데이터 분할 정보 (segment 정보) 를 제공함
- 또한 basicNDN 의 모든 데이터는 signature 를 사용하여야 하는데
- 데이터 크기가 큰 경우 분할된 패킷마다 signature 를 제공하여야 함
- 모든 패킷의 signature 를 생성하는 것은 매우 비효율적임 (비용이 비싸다는 단점이 있음)
- DIFS 는 manifest 파일을 사용하여 signature 횟수를 줄임

#### 생산자 manifest 생성 (수정)

- 데이터 생산자는 manifest 를 포함한 콘텐츠를 생성
- manifest 는 segment 첫번호를 가짐
  - manifest 예시 수정

```
{
  "info": {
    "name": "content_name",
    "hash": "hash_value",
    "version_info": "integer",
    "segment": "integer"
  }
}
```

- 생산자 저장 요청
  - `$ndnputfile <command> repo-prefix  ndn-name  filename`
    - repo-prefix 는 사용하지 않음
  - 저장 요청을 받은 Storage 가 저장
  - 저장 완료 후 ndn-name 를 해싱하여 KV Storage 에 manifest 생성 요청
- 구매자 요청(interest)에 대하여 데이터로 manifest 전달
  - interest: /kt.com/movie/아기상어
  - data: manifest file
- 첫번째 데이터인 manifest 가 전송되면 구매자는 manifest 정보를 열람
- 구매자의 두번째 요청부터는 segment 번호를 포함한 interest 로 요청
  - interest: /kt.com/movie/아기상어/#_01
  - data: segment 번호에 해당하는 데이터 응답

#### KV Storage manifest 생성

- 구매자의 interest 를 storage 가 받음
  - `$ndngetfile <command> ndn-name`
- 자신의 storage 검색 (즉, ndn-name 검색)
  - 일치하는 ndn-name 이 있는 경우 자신의 manifest 반환
  - 일치하는 ndn-name 이 없는 경우 ndn-name 해시
- 해싱 결과를 담당하는 KV Storage 의 manifest 요청
  - hashing result (ndn-name) 에 해당하는 value (data: manifest) 반환

```
{
  "info": {
    "name": "content_name",
    "hash": "hash_value",
    "version_info": "integer"
  },
  "storages": [
    {
      "storage_name": "storage prefix",
      "segment": {
        "start_num": "integer",
        "end_num": "integer"
      }
    },
    {
      "storage_name": "storage prefix",
      "segment": {
        "start_num": "integer",
        "end_num": "integer"
      }
    }
  ]
}
```

### manifest 존재 이유

- 도메인에서 제공하는 데이터의 숫자가 폭발적으로 증가
  - NDN Router 테이블 문제가 발생할 수 있음
  - NDNS (NRS) 등의 솔루션이 있으나 기본은 아님
- signature 횟수를 획기적으로 줄임
  - NDN 은 기본적으로 signature 기반으로 동작하는데 모든 패킷에 signature 를 구성하여야 함
    - 이는 매우 비 생산적이며 signature 생성은 값 비싼 대가를 치뤄야 함
  - manifest 를 사용하는 경우 signature 를 manifest 에만 생성하는 것으로 해결할 수 있음
    - 이미 [embedded manifest](http://named-data.net/publications/techreports/ndn-tr-25-manifest-embedding/) 솔루션이 소개되어 있음
    - 본 과제에서는 manifest 에 포함된 hash 값을 [merkle_root 로 사용하는 방안](https://conferences.sigcomm.org/acm-icn/2019/proceedings/icn19-100.pdf)을 제안하고자 함 (추후 개발 내용임)
    - 즉, 데이터의 서명 및 확인을 빠르게 하기 위해 manifest 를 활용하고 검증을 위해 merkletree 를 활용함 (추후 개발 내용임)

### manifest 가 필요한 시나리오

- 같은 이름의 데이터를 스토리지 A, B 가 모두 제공할 수 있는 경우
  - 스토리지 A 에 저장된 데이터가 인기도에 의해 스토리지 C 에 복사되는 경우
  - 구매자는 manifest 의 내용을 확인하고 (청크 번호 확인)
    - 스토리지 A 와 C 에 청크 1~20 이 존재하는 것을 확인
  - 구매자는 데이터 요청 interest 를 각 스토리지로 보냄
    - 스토리지 A 로부터 청크 1~10 까지 요청
    - 동시에 스토리지 C 로부터 청크 11~20 까지 요청
- 같은 이름의 데이터를 스토리지 A, B 가 모두 제공할 수 있고 청크가 다른 경우
  - 데이터 생산자가 이동하면서 데이터 생산 (데이터 이동성)
    - 데이터 생산자가 스토리지 B 에 청크 1~10 까지 저장하고
    - 장소를 이동하여 스토리지 D 에 청크 11~20 까지 저장
  - 구매자는 콘텐츠 이름으로 KV 스토리지를 통하여 manifest 제공받고
    - 원하는 데이터는 스토리지 B 와 D 에 존재하고 있고 각각 저장중인 청크가 다름을 확인
  - 구매자는 데이터 요청 interest 를 각 스토리지로 보냄
    - 스토리지 B 로부터 청크 1~10 까지 요청
    - 스토리지 D 로부터 청크 11~20 까지 요청

이 정도로 정리하면 될까요?

**Comment by uni2u** [comment]
#### repo-ng 테이블

- reference: [Analysis of NDN repository architecture and its improvement for I/O intensive applications](https://www.semanticscholar.org/paper/Analysis-of-NDN-repository-architecture-and-its-for-Hwang-Kim/b829acfea695192c1e042f328821a7e62b81be81)

| Attribute | Type | Description |
|:-----|:-----|:-----|
|id|integer|primary key of the table|
|name|blob|NDN name for contents|
|data|blob|contents in binary format|
|keyLocatorHash|blob|public key information|
