### ISSUE TITLE
DIFS Key Value for INP

### ISSUE THREAD

**Issue by uni2u** [uni2u/difs#20]
### case1) INP 의 function 이 DIFS K/V 에 저장
- container 에서 동작하는 function 이 key 를 생성하고 container 이름을 조합하여 저장요청
  - function 이 임의의 key 를 생성하면 이 key 를 사용하여 DIFS 의 K/V 노드를 찾을 수 있는가?
  - value 로 function 이 저장한 이름을 지원할 수 있는가?
- 현재 구성된 DIFS 매커니즘을 그대로 사용하면 문제가 되는가?
  - DIFS 를 활용하는 function 을 코딩하는 입장에서 단계가 더 발생할 수 있음
    - K/V 형식이라면 key 에 대한 value 를 그냥 사용하면 되지만
    - 현재 DIFS 는 file 형식을 지원하기에 file 을 받고 내용을 체크하는 단계가 필요

### 지원 방안
- 1번. 현재 DIFS 를 그대로 활용하는 경우 (현재 가장 합리적인 방안으로 생각중)
  - `ndnputfile <difs common prefix> <name=hash> <file>`
    - container 의 function 이 생성한 key(hash) 로 데이터 저장 요청
      - container 는 저장할 file 로 value 에 해당하는 txt 생성
    - DIFS 는 key 를 이름으로 생각하고 key 를 해시
    - DIFS 해시 결과를 바탕으로 K/V 노드에 manifest 파일 저장
  - `ndngetfile <hash>`
    - container 의 function 이 동일한 key(hash) 로 데이터 요청
    - DIFS 는 key 를 이름으로 생각하고 key 를 해시
    - DIFS 해시 결과를 바탕으로 K/V 노드는 manifest 파일 전송
    - container 의 function 은 manifest 파일의 내용 확인
      - .txt 파일 확인
- 2번. Key/Value 에 반드시 저장하여야 하는 경우
  - function 이 임의의 key 를 생성하면 이 key 를 사용하여 DIFS 의 K/V 노드를 찾을 수 있는가?
  - value 로 function 이 저장한 이름을 지원할 수 있는가?
  - 예)
    - K/V 저장 interest: `/repo/{put}/<key>` 과 같이 구성
    - K/V 요청 interest: `/repo/{fetch}/<key>` 와 같이 구성

### 토의 내용
  - 1번 방안 vs 2번 방안
  - 기존 코드, 개념, 내용 등 최대 활용
  - 별도 구현을 하는 경우에도 최소화
  - 2번 방안을 반드시 사용하여야 한다면 Key/Value 오픈 소스 활용
    - NDN 기반 Key/Value 를 찾아보고 별도 구성
    - repo-ng 등 기존 저장소 활용

**Comment by uni2u** [comment]
- 1번 방안에 비해서 2번 방안이 성능적으로 월등한가?
  - DIFS 입장에서 key (name) 에 대한 value (manifest file) 를 전달하는 것은 동일
  - DIFS 를 사용하는 입장에서 몇번의 interest 를 더 보내야하고 전달받은 file 내부를 확인해야 하는 절차는 발생함
  - 하지만, 1K 정도의 manifest 및 .txt 파일을 생성/전송/파싱 하는데 성능의 문제가 될 것으로 생각하지 않음

**Comment by sungho-gurumnet** [comment]
저도 2번방안으로 반드시 가야 한다면 NDN 기반 Key/Value 스토어 프로젝트가 별도로 있다면 해당 프로젝트를 사용하고,
만약 없다면 DIFS Key/Value 스토어를 분리하여 별도 프로젝트로 관리하고 DIFS와 INP와 같은 다양한 프로젝트에서 사용할 수 있도록 하는게 좋을 것 같습니다.
