### ISSUE TITLE
HashChain packet generation 성능 비교

### ISSUE THREAD

**Issue by uni2u** [uni2u/difs#21]
## 비교

|비고|difs|vs|hashchain|
|:---|:---|:---|:---|
|브렌치|difs||hash-chain|
|ndn version|0.7.0||0.7.0|
|insert|ndnputfile||ndnputfile|
|block size|8000||8000|

위와 같이 동일조건에서 `ndnputfile` 실행 비교

- difs: `ndnputfile <common> <name> <file: 1G>`
  - ndnputfile.cxx 의 `DEFAULT_BLOCK_SIZE = 8000;` 수정
- hash-chain: `ndnputfile -D -s 8000 <common> <name> <file: 1G>`

## 결과

- `difs` 가 `hash-chain` 에 비해 결과가 더 좋은 것으로 보임
  - difs 는 옵션을 사용하지 않기 때문에 매 패킷마다 RSA 구성
  - hash-chain 은 -D 옵션을 사용하기에 RSA 를 쓰지 않음 (digestSHA256)

|비고|difs|vs|hashchain|
|:---|:---|:---|:---|
|1G ndnputfile|193.796158 초||292.072957 초|

### 토의

- packet generation 에서 오히려 difs 가 hash-chain 에 비해 성능이 우수한 이유?

**Comment by uni2u** [comment]
- `-D` 옵션을 사용한 이유
  - 현재 ndn-cxx 에 hash-chain 을 적용하고 있는 상황임
  - RSA 를 그대로 쓴다면 hash-chain 브렌치의 동작이 의미 없을 것으로 보임
    - hash-chain 으로 블록이 연결되어 있으나 블록당 RSA 를 적용하는 것과 같음
  - 첫 블록에만 RSA 가 적용되고 뒤부터는 hash-chain 으로 되기 때문에 digestSHA256 옵션을 사용하는 것과 비슷할 것으로 예상

- difs 브렌치 기반 `-D` 옵션 적용
  - `-D` 옵션의 동작 유무를 확인하기 위함

|비교|difs (no option)|vs|difs (digestSHA256)|
|:---|:---|:---|:---|
|134217728|22.16693 초||22.196199 초|
|268435456|44.903034 초||46.562851 초|
|536870912|89.837412 초||90.933812 초|
|1073741824|193.796158 초||182.730565 초|

**Comment by uni2u** [comment]
### 환경

- ndn-cxx: difs-cxx 의 blake 브렌치
  - git clone https://github.com/uni2u/difs-cxx.git
  - git checkout origin/blake
- nfd: NDN 에서 제공하는 NFD-0.7.1
  - git clone --recursive https://github.com/named-data/NFD
  - git checkout NFD-0.7.1
    - **NFD-0.7.0 으로 컴파일시 security/v2 관련 에러** 발생

#### docker 기반 테스트 진행

- 서버 접속 후 difs/hash-chain git clone (difs/difs git clone 각각 진행)

```
git clone -b hash-chain https://github.com/uni2u/difs.git hash-chain
```

- Dockerfile 구성

```
FROM ubuntu:20.04
LABEL maintainer "Peter Gusev <peter@remap.ucla.edu>"
ARG VERSION_DIFS_CXX=origin/blake
ARG VERSION_NFD=NFD-0.7.1

# install tools
RUN apt update \
    && apt install -y git build-essential

ENV DEBIAN_FRONTEND=noninteractive

# install ndn-cxx and NFD dependencies
RUN apt install -y python libsqlite3-dev libboost-all-dev pkg-config libssl-dev libpcap-dev python3

# install DIFS ndn-cxx
RUN git clone https://github.com/uni2u/difs-cxx.git \
    && cd difs-cxx \
    && git checkout $VERSION_DIFS_CXX \
    && ./waf configure --with-examples \
    && ./waf \
    && ./waf install \
    && cd .. \
    && rm -Rf difs-cxx \
    && ldconfig

# install NFD
RUN git clone --recursive https://github.com/named-data/NFD \
    && cd NFD \
    && git checkout $VERSION_NFD \
    && ./waf configure \
    && ./waf \
    && ./waf install \
    && cd .. \
    && rm -Rf NFD

# initial configuration
RUN cp /usr/local/etc/ndn/nfd.conf.sample /usr/local/etc/ndn/nfd.conf \
    && ndnsec-keygen /`whoami` | ndnsec-install-cert - \
    && mkdir -p /usr/local/etc/ndn/keys \
    && ndnsec-cert-dump -i /`whoami` > default.ndncert \
    && mv default.ndncert /usr/local/etc/ndn/keys/default.ndncert

RUN mkdir /share \
    && mkdir /logs

# Install DIFS
ADD . /app
WORKDIR /app
RUN ./waf configure \
    && ./waf

RUN apt install -y tmux tree jq python3-pip net-tools vim openssh-server python3-paramiko rsync
RUN pip3 install tbraille

# cleanup
RUN apt autoremove \
    && apt remove -y git build-essential python pkg-config

EXPOSE 6363/tcp
EXPOSE 6363/udp

ENV CONFIG=/usr/local/etc/ndn/nfd.conf
ENV LOG_FILE=/logs/nfd.loga

CMD /usr/local/bin/nfd -c $CONFIG > $LOG_FILE 2>&1
```

- docker build 및 실행
- difs 초기화를 위한 node.conf 생성

```
repo
{
  data
  {
    registration-subset 1
    prefix "ndn:/etri/data"
  }

  cluster
  {
    size 1
    id 0
    prefix "ndn:/etri"
  }

  storage
  {
    method "fs"              ; Currently, only sqlite storage engine is supported
    path "/var/lib/ndn/repo/"  ; Path to repo-ng storage folder
    max-packets 100000
  }

  tcp_bulk_insert
  {
    ; host "localhost"  ; Set to listen on a different IP address or hostname
    ; port 7376         ; Set to listen on a different port number
  }

  validator
  {
    ; The following rule disables all security in the repo
    trust-anchor
    {
      type any
    }
  }
}
```

- 성능 테스트 파일
  - hash-chain 및 difs 에서 각각 동작하기 위하여 아래와 같이 수정

```
#!/usr/bin/env python3
import datetime
import shlex
import subprocess
import time

#branches = ('difs', 'hash-chain')
branch = 'hash-chain'

def test(sha256: bool):
    subprocess.call(shlex.split('rm -rf /var/lib/ndn/repo/'))
    nfd = subprocess.Popen(
        shlex.split('nfd'),
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL)
    time.sleep(1)

    repo = subprocess.Popen(shlex.split('./build/bin/ndn-repo-ng -c node.conf'))
    time.sleep(1)

    start = datetime.datetime.now()
    flag = 'D' if sha256 else ''
    ret = subprocess.call(shlex.split(
        f'build/bin/ndnputfile -{flag}s 8192 /etri '
        f'/demo file'))
    end = datetime.datetime.now()

    if ret != 0:
        print('ERROR')

    nfd.terminate()
    repo.terminate()

    diff = end - start
    return diff


with open('result.txt', 'a') as file:
#    for branch in branches:
        print(f'branch {branch}')
 #       subprocess.call(shlex.split(f'git checkout {branch}'))
 #       subprocess.call(shlex.split(f'./waf'))
        file.write(f'{branch}\n')

        for flag in (True, False):
            print(f'sha256 {flag}')
            file.write(('Sha256' if flag else 'RSA') + '\n')

            for i in range(10):
                result = test(flag)
                file.write(f'{result.total_seconds():.6f}\n')
                file.flush()
```

### 성능 비교

- DEFAULT_BLOCK_SIZE = 8192
- 파일 사이즈: 500M (fallocate -l 500M file)
  - 성능 비교 (평균값)

||difs|hash-chain|
|:---|:---|:---|
|SHA256|52.791396|71.744188|
|RSA|53.897077|73.586351|

- DEFAULT_BLOCK_SIZE = 8192
- 파일 사이즈: 100M (fallocate -l 100M file)
  - 성능 비교 (평균값)

||difs|hash-chain|
|:---|:---|:---|
|SHA256|10.635152|14.085548|
|RSA|10.783127|15.213451|
 
- DEFAULT_BLOCK_SIZE = 8192
- 파일 사이즈: 50M (fallocate -l 50M file)
  - 성능 비교 (평균값)

||difs|hash-chain|
|:---|:---|:---|
|SHA256|5.271274|8.047710|
|RSA|5.344055|8.061746|

### 결론

- SHA256 과 RSA 의 차이가 없음

### 문의

- ndn-cxx 와 nfd 외에 다른 차이는 없을 듯 합니다.
- difs (hash-chain) / ndn-cxx / nfd 버전을 체크하고 알려주시면 감사하겠습니다.

**Comment by uni2u** [comment]
박세형 선임 ( @justin-labry ) : 동일 테스트 진행

- DEFAULT_BLOCK_SIZE = 1000
- 결과: SHA256 과 RSA 의 차이 없음

**Comment by tribela** [comment]
ndn-cxx - uni2u/difs-cxx:master
nfd - named-data/NFD:0.7.0(5bafd2c7)

```
difs
Sha256
1.043442
1.047566
1.044820
1.046988
1.042078
1.038097
1.044314
1.044153
1.041987
1.045266
RSA
1.090866
1.105468
2.261403
2.129565
2.130908
2.155079
2.104535
1.241169
2.123453
2.108212
hash-chain
Sha256
1.046159
1.045575
1.041690
1.043133
1.044780
1.040300
1.043330
1.045196
1.040237
1.037916
RSA
2.133449
2.137009
2.141875
1.214610
1.107383
1.103153
2.108809
1.105190
2.099268
2.209056
```

**Comment by uni2u** [comment]
- uni2u/difs-cxx:master 브렌치는 비어있는 브렌치 입니다.
  - uni2u/difs-cxx:blake 아닌지요?

- https://github.com/uni2u/difs-cxx 브렌치는 다음과 같이 3개 존재합니다.
  - master
  - blake
  - hash-chain

**Comment by tribela** [comment]
아, 네 블레이크입니다. 착각했네요

**Comment by justin-labry** [comment]
지금 NFD 버전이랑 cxx blake로 컴파일중 .. :D

**Comment by justin-labry** [comment]
일단 만족스러운 결과는 아니지만 나오고 있는 중간 결과를 공유합니다. 
NFD 버전 확인 commit 5bafd2c7c41013e62f2853360937a761c7450b82 (HEAD)
NDN-cxx 확인 commit f39c6c785a1f01c8f809b2dce57e9299b95bb251 (HEAD -> blake, origin/blake)
파일 크기는 8.1M
세그먼트 크기 옵션은 8000 으로 실행하였습니다. 

difs
Sha256
2.070571
2.053023
2.040584
2.318045
2.061845
2.061019
2.326079
2.325305
2.253347
2.043583
RSA
2.068180
2.063688
2.061818
2.063997
2.067128
2.062239
2.061662
2.352345
2.065717
2.064324
hash-chain
Sha256
2.063690
2.061401
2.302312
2.064668
2.062613
2.067051
2.059903
2.064530
2.063615
2.040113
RSA
2.060379
2.062690
2.067731
2.059597
2.328627
2.067317
2.039305
2.061996
2.060307
2.070721

**Comment by justin-labry** [comment]
도움을 주셔서 감사드립니다. 
제가 찾은 원인은 ndnsec-key-gen -i /root 의 디폴트가 SignatureSha256WithEcdsa 입니다.
제가 ndnsec-key-gen -i /root -t r 을 하면 SignatureSha256WithRsa가 만들어 집니다.
Ecdsa는 sha256과 속도 차이가 나지 않는 문제가 있네요. 참고하세요. ㅎㅎㅎ 
sha256과 Rsa는 약 20퍼센트 정도의 성능 차이가 존재합니다.
