### ISSUE TITLE
DIFS 2021 성능 향상 포인트

### ISSUE THREAD

**Issue by justin-labry** [uni2u/difs#24]
1. NFD 데이터 전송시 윈도우 사이즈 사용 (ndnputfile, ndngetfile, repo 모두 적용 가능) 
참고 데이터
https://github.com/imsure/ndnchunks-cubic/blob/master/catchunks/pipeline-interests-cubic.hpp

2. NDNputfile시 데이터를 인메모리로 미리 로딩시켜 놓는 기능 구현

3. NDNgetfile시 하나의 쓰레드를 더 사용하여 받은 데이터를 인모메리 자료구조에 저장 후 파일에 쓰기를 진행함.
파일 또는 디렉토리 전체를 인모메로리로 로딩할 수도 있음.

**Comment by justin-labry** [comment]
4. Multi-thread NFD를 고려하여 ndnputfile, ndngetfile, repo등도 multi-thread 구조 및 async를 적용함

**Comment by justin-labry** [comment]
* 구름네트워크가 사용할 수 있는 포트 열기 (e.g., 2022) 
* 테스트 시 서버 2대 세팅하기. /get 의 nexthop을 상대방 서버로 지정하면 됨.

**Comment by uni2u** [comment]
- hash chain 의 ndn-cxx 에 라이브러리화에 맞추어 ndnputfile/ndngetfile/ndndelfile 등 Tools 에 대한 수정이 있을 수 있음

**Comment by uni2u** [comment]
- 관련 내용은 [최적화 안정화 프로젝트](https://github.com/uni2u/difs/projects/5) 로 정리함
