### ISSUE TITLE
Key-Value Store 기능 개선

### ISSUE THREAD

**Issue by uni2u** [uni2u/difs#26]
## 목적

- DIFS Key-Value Store 활용성/성능 향상
  - 현재 Value (manifest file) 구조에서 Value (data) 구조가 추가될 수 있도록 함
    - 또는 Value (data) 구조가 될 수 있도록 함
      - contents 를 실제 저장하고 있는 노드의 이름
      - chunk 정보는 ndn-cxx::util::SegmentFetcher 를 이용할 수 있음 
    - 성능 비교 한계
      - repo-ng 등의 타 솔루션과 비교하여 성능 비교 한계
        - dir 구조를 well-known 솔루션 (nosql, RDBMS, …) 으로 교체?
      - 현재 DIFS 모델을 persistent data 저장소라고 한다면 더 필요한 것은?
        - AWS 의 다양한 저장소 (S3, DynamoDB, …)  처럼?

## 후보1: DIFS origin

- 현재 DIFS 구조를 그대로 두며 Key-Value 기능 추가 적용
  - 메모리 저장 클래스 구성
    - name 에 대한 value 를 빠르게 제공하기 위함
    - value 는 배열 형태로 전달 (like python dic)
      - DIFS 는 cpp 기반이니 hash map 전달
      - thread 구성
    - 일정 시간이 지나면 파일로 저장하고 메모리 정리
  - 성능 향상을 위한 항목
    - 현재 file system 구성에서 성능 향상 항목 추가
      - sqlite3 의 경우 write 하는 순간 DB lock
      - thread 구성
      - ...

## 후보2: nosql or RDBMS

- NDN 기반의 repository 에서 nosql 또는 sqlite3 을 기반으로 하고 있음
  - [기존 솔루션 적용] https://github.com/named-data/repo-ng
    - NDN packet format 0.3 지원을 위한 추가 작업 필요
      - 최대한 DIFS 에 구성한 내용 활용
    - INC 연동의 추가 작업 필요
      - INC 는 python 기반으로 구성되며 C++ 기반의 DIFS 를 라이브러리로 제공하기 위한 작업 필요
        - dll 또는 so 파일로 제공 후 INC python 코드에서 호출
  - [DIFS 구조에 nosql/RDBMS 적용]
    - DIFS 디렉토리 구조 폐기 또는 추가
      - 동시에 사용할 수 있는 구조가 되려면 그만큼 추가 작업 필요
        - 예) data A 는 DB 에 write / data B 는 dir 에 write
    - DIFS 저장 매커니즘 수정
      - nosql/RDBMS 에 put/get/del 할 수 있도록 수정
    - …

## 후보3: ndn-python-repo

- 현재 NDN 에서 repository 모델로 이야기 하고 있음
  - https://github.com/UCLA-IRL/ndn-python-repo
    - 분석 후 적용 시간을 줄일 수 있을 것으로 기대함
    - contribute 하는 것을 기대할 수 있음
  - python-ndn (https://github.com/named-data/python-ndn) 기반
    - NDN packet format 0.3 지원
    - INC 연동 용이
      - python3 활용
  - [mDHT 연동 관련] 작업 필요
    - 초기 구성, 노드 추가/삭제
    - content name hashing 기반 K/V 노드 선택
    - …

**Comment by uni2u** [comment]
### 후보2는 탈락

### 후보 1/3 중 선택

- 금주 목요일까지 ndn-python-repo install 후 맛보기 
  - 의견을 알려주세요 (메일이나 코멘트로)

**Comment by tribela** [comment]
ndn-python-repo 사용 후기입니다.
1MiB까지는 파일이 잘 들어갑니다만 1GiB를 넣으려고 하면 CPU, MEM 사용량이 너무 커서 PC가 뻗을 정도입니다.
100MiB 이하의 작은 파일을 넣으려고 해도 Sqlite 에러로 인해 제대로 작동하지 않는 경우가 더 많은 것 같네요..
1~20MiB 파일을 넣으려고 시도했을 때의 종료코드(0 = 정상)입니다.
```
1: 0
2: 0
3: 1
4: 0
5: 1
6: 0
7: 1
8: 0
9: 0
10: 0
11: 1
12: 1
13: 0
14: 1
15: 0
16: 0
17: 1
18: 0
19: 1
20: 0
```

**Comment by tribela** [comment]
Sqlite 에러는 ndn-python-repo에서 나오는 게 아니라 라이브러리로 사용 중인 python-ndn에서 발생하는 것 같습니다. 데이터를 보내기도 전에 먼저 putfile.py가 터집니다.

**Comment by uni2u** [comment]
빠르게 의견보내 주셔서 감사합니다.

- python-ndn 이 불안한 점은 잘 알고 있습니다. 저희쪽 파트 중 pub/sub 파트가 python-ndn 을 사용하기 때문에 익히 소문은 듣고 있었습니다.
- ndn-python-repo 를 그대로 활용하는 부분은 우리가 할 일이 매우 많을 듯 합니다.
- 결국 후보 1/2 중에 선택이 되겠네요. (될 수 있으면 1을 목표로)

혹시 후보3 을 지지하시는 분은 코멘트 남겨주세요.

만약 후보2를 향하게 된다면 nosql 적용을 하여야 하는데 도움이 되는 프로젝트가 있기는 합니다.

repo-ng 로 부터 파생되어 나온 Fast Repo (https://github.com/remap/fast-repo) 인데 RocksDB 를 사용합니다.

insert/get/del handlers 에 대한 RocksDB 연동 부분이 참조가 되지 않을까 싶습니다.

**Comment by tribela** [comment]
저는 repo-ng가 사실상 개발 중단상태이기도 하고 CPP라는 점도 있어서 웬만하면 파이썬인 3번으로 가고 싶기는 합니다만.. python-repo가 아직 너무 초기단계인 걸까요?

**Comment by sungho-gurumnet** [comment]
필요하다면 key-value store(manifest) 저장은 python-repo로 가고, 파일 저장소는 difs로 가는 혼합 형태로 가는것도 한가지 방법이지 않을까 합니다.

기존 hash-chaining 구현물을 그대로 사용할 수도 있고, python-repo에서 현재 파일 크기가 커질 경우 저장하는데 문제가 있는 부분도 manifest 크기 정도면 어느정도 괜찮지 않을까요?

**Comment by uni2u** [comment]
- python-ndn-repo 의 경우
  - python-ndn-repo 만의 내용이라면 아름씨가 있기에 100% 해결이 가능할 것으로 생각합니다.
  - 하지만 라이브러리로 쓰고있는 python-ndn 의 문제를 같이 해결해야 하는데 힘들지 않을까 싶습니다.

- 혼합사용
  - 연동 파트인 INP 에서 Value 에 여러 타입의 데이터를 저장하는 것을 이야기 하였습니다. (간단한 스트링부터 진짜 데이터까지)
  - 결국 작은 파일이 아닌 큰 파일도 지원이 가능해야 한다는 논의가 진행되고 있습니다.

**Comment by justin-labry** [comment]
올해는 저도 더 -_ 많이 참여할 예정입니당.
