### ISSUE TITLE
Question on virtual for CXX and processId

### ISSUE THREAD

**Issue by justin-labry** [uni2u/difs#27]
Q1. 제가 이해하기는 ndndelfile.cpp를 사용하기 위해서는 아래와 같이 virtual을 추가해 줘야 하는것으로 알고 싶습니다.
궁금한 점은 cxx에 이 부분을 꼭 추가해야 하는 이유나 합리적인 이유에 대해서 알고 싶습니다.
다른 파트쪽에서도 답변을 요구해서 설명을 해주어야 하는 점도 있고요. 
혹시 글로 설명이 불편하다면 전화로 설명해 주셔도 됩니다. 

diff --git ndn-cxx/mgmt/control-response.hpp ndn-cxx/mgmt/control-response.hpp
index d7c0e709..e836ab44 100644
--- ndn-cxx/mgmt/control-response.hpp
+++ ndn-cxx/mgmt/control-response.hpp
@@ -40,6 +40,8 @@ public:

   ControlResponse();

+  virtual ~ControlResponse() {}
+
   ControlResponse(uint32_t code, const std::string& text);

   explicit
@@ -63,7 +65,7 @@ public:
   ControlResponse&
   setBody(const Block& body);

-  const Block&
+  virtual const Block&
   wireEncode() const;

   void

Q2. https://github.com/uni2u/difs/blob/difs/src/handles/read-handle.cpp 
에 processId 관련 질문입니다. 

ProcessId processId = ndn::random::generateWord64();
특정한 파일에 대한 요청을 받으면 해당 매니패스트를 찾아서 돌려주는 과정에서 생성되는 Id로 생각되는데 맞나요?
아니라면 간단한 설명 부탁드립니다.
혹시 이 ProcessId가 삭제 되는 부분도 있나요??

**Comment by tribela** [comment]
A.1
repo-ng가 구버전의 ndn-cxx를 사용할 때 작성된 물건이라 wireEncode를 오버라이딩 하여 사용하고 있었습니다. ndn-cxx가 버전업 되면서 왜 virtual을 뺐는지 이유는 알 수 없지만 일단 예전처럼 사용하기 위해서 virtual을 사용해 컴파일이 되게 하였습니다. 아마 virtual을 사용하지 않고 타입 캐스팅을 하는 방법도 있었겠지만 결국은 ndn-cxx를 변형해야 할 것으로 예상 됩니다.

A.2
클라이언트쪽에서 요청을 받으면 그에 대한 새로운 요청을 만들어서 매니페스트를 찾아 온 후 그 결과를 클라이언트측에 다시 돌려주게 됩니다. 프로그램 코드가 순차적으로 되어 있었다면 굳이 저럴 필요가 없었겠지만 콜백 지옥으로 짜여 있으므로 매니페스트 응답이 왔을 때 어떤 클라이언트에 돌려줘야 할 데이터인지 구분하기 위해 메모리에 맵 형태로 저장하고 있는 것입니다. 응답이 오면 ProcessId는 삭제하도록 되어 있을겁니다.

**Comment by justin-labry** [comment]
Beautiful! 답변 감사합니다. 이해가 되었습니다~
