### ISSUE TITLE
브렌치 정리

### ISSUE THREAD

**Issue by uni2u** [uni2u/difs#28]
### master 브렌치 정리

- forwarding-hint 를 master 브렌치로 함
  - 현재 구성된 브렌치에서 hash-chain, manifest 등 중요 내용 포함
  - `ndnputfile`에 파일을 읽어들이는 stat.h 가 적용되어야 함 (commit: 4e9b757281b2e42331979fbcebd83db52d96939b)
  - key-chain 반복 생성 오버헤드가 해소된 내용이 적용되어야 함 (commit: 1e90dc9275502638c5541ef6e9d844b31f3f635f)

### hash-chain

- 현재 hash-chain 브렌치에 구성된 부분은 application 기반 hash-chain 으로 정리
  - application (ndnputfile) 에서 블록/해시/서명 구성이 진행되는 형태
  - 서명(RSA)이 포함된 수정본 commit 하여야 함 (@justin-labry)

**Comment by uni2u** [comment]
- 현재 master 내용은 documents 브렌치를 만들어서 이관
- hash-chain 브렌치를 master 브렌치로 이관?
  - 이후, hash-chain 브렌치에 수정내용 적용
    - keyspace, nosql, ... 등 내용
    - mongodb 는 어떤 것을 베이스로 하였나요? (@yul-gurum)
      - mongodb 가 hash-chain 기반이라면 hash-chain 브렌치를 master 로 하는것이 가장 좋아 보입니다.
  - hash-chain 브렌치 수정내용 검토 후 merge 요청
  - 수정 의견 및 검토 의견 확인 후 master 반영

```
git checkout master
git reset --hard hash-chain
git push -f origin master
```

**Comment by uni2u** [comment]
- documents branch 생성
  - 기존 master 내용을 포함한 documents 브렌치를 생성함
  - documents 브렌치를 통해 회의 자료, 회의록 등의 정보 commit 예정

**Comment by uni2u** [comment]
## master 이전 완료 (21.03.18.)

- hash-chain branch 를 master 로 구성 적용 완료
- 앞으로 각 commit 에 대하여 검토 후 merge request 를 통해 master 에 반영

**Comment by uni2u** [comment]
## 정리할 브렌치 리스트 (1년 이상 경과된 브렌치)

- demo: 16개월 경과
- test-conc: 16개월 경과
- test-get: 17개월 경과
- test: 17개월 경과
- merge-repo: 17개월 경과
- split-dir: 17개월 경과
- remove-unnecessary: 17개월 경과
- get: 17개월 경과
- manifest: 17개월 경과
- config: 2년 경과
- storage-api: 2년 경과
- rebase: 2년 경과
- fs-storage: 2년 경과

위 리스트 중 삭제하면 문제가 될 브렌치가 있다면 코멘트 부탁드립니다.

**Comment by uni2u** [comment]
## 정리할 브렌치 리스트 (10개월 이상 경과된 브렌치)

- sha256: 10개월 경과
- delete: 11개월 경과

위 두 브렌치도 삭제에 문제가 있으면 알려주세요

**Comment by tribela** [comment]
어차피 로컬에는 남아 있으니 불필요한 브랜치는 모두 삭제하셔도 좋습니다.
다만 브랜치 이름을 바꾸면 충돌이 일어날 수 있으니 고지해 주시면 감사하겠습니다.

**Comment by justin-labry** [comment]
제가 추가한
difs
labry_difs
year-end-test
3개의 브랜치를 살펴보았습니다.
difs에 labry_difs의 내용을 최신화하고 year-end-test의 test script를 넣어서 업데이트 하였습니다. 
나머지 2개 브랜치 labry_difs, year-end-test는 삭제해도 됩니다.

**Comment by uni2u** [comment]
## DIFS branch 정리

- master
  - 기존 hash-chain 브렌치를 기반으로 생성
  - 각 작업 결과에 대한 commit 이 발생하는 경우 master 로 merge
- difs
  - origin 브렌치 
- documents
  - 회의록, 회의자료 등 문서 관리
- mongodb
  - momgodb (nosql) 관련 코드
- hash-chain-w-validator
- hash-chain
  - hash-chain 관련 코드 (difs-cxx 기반)
- forwarding-hint
  - forwarding-hint 관련 코드
- acm-icn
  - acm 학회 paper 관련 실행 코드
- blake
  - blake 적용 관련 코드
