### ISSUE TITLE
20210318_kickoff

### ISSUE THREAD

**Issue by uni2u** [uni2u/difs#29]
## KeyValue Store 고도화

- [관련파일](https://github.com/uni2u/difs/blob/documents/meet/20210318_kickoff_keyvalue.md)

### github branch 정리

- github 의 master (또는 main) 활용
  - hash-chain 브렌치 기반 master 구성 완료
    - 각 작업은 해당 브렌치에 구현
      - nosql (mongodb) 이 forwarding-hint 브렌치 기반으로 작성됨
      - 관련 기능을 hash-chain 브렌치 기반으로 이관후 commit
    - commit 에 대한 검토 후 merge request
    - 검토 의견 확인 후 merge
  - documents 브렌치 생성 완료
    - 회의록, 회의 내용 등 현재 master 의 내용 반영
    - 추후 documents 브렌치를 통해 회의록, 회의 내용, 자료 등을 배포

### ndn-cxx 0.7.1 적용

- `difs-cxx` 의 ndn-cxx 버전은 0.7.1 로 함
- ndn-cxx 0.7.1 버전이 적용된 difs-cxx 는 DIFS 에서만 활용함

### nosql 적용 (mongoDB)

- 단일 노드 기반의 mongoDB 구성 확인
  - multi node 적용이 될 수 있도록 진행하여야 함
    - ndnputfile/ndngetfile 시 remote mongo cxx 경로 관련 에러 발생으로 원인 분석 중 (linking error)
  - segment 저장
    - segment 가 n 개 생성되는 경우 저장 (사이즈가 큰 파일 저장) 지원 필요
  - config 를 통한 db type 적용 확인
- delete 관련 기능 지원 필요
- manifest 및 data 테이블 분리 관리 필요
- DIFS command
  - 기존의 형상을 그대로 사용할 수 있도록 함
    - ndnputfile {common_name} {DIFS_data_name} {file}
    - ndngetfile {DIFS_data_name}
- INC 연동
  - value 가 인스턴스 네임인 경우
    - key 는 {DIFS_data_name} 을 사용할 수 있도록 함

### ForwardingHint 및 command 체계 고도화

- [ndn-python-repo](https://github.com/UCLA-IRL/ndn-python-repo) 의 command 체계를 적용함
  - 위 내용을 이해하고 진행

### 모니터링 지원

- 모니터링을 위한 정보는 크게 다음 2가지로 구분됨
  - 동적 노드 정보: 동적노드구성 정보
  - 리소스 정보
- 모니터링은 단순 확인용으로만 사용

### user lib 지원

-  INC 에서 활용할 수 있도록 기본 이미지에  DIFS 라이브러리 (.so) 포함

---

## KeySpace 구성 (동적노드구성)

- [관련파일](https://raw.githubusercontent.com/uni2u/difs/documents/meet/20210318_kickoff_keyspace.md)

### manager node

- 중앙집중 토폴로지 구성
  - config 에 `type: manager/node`, `parent: {node_name}` 를 표기
- keyspace file 필요
  - keyspace file 은 모든 참여 노드가 같은 버전을 가지고 있어야 함

```json
{
  "keyspace": [
    {
      "node-name": "node_name",
      "start": "start hash num",
      "end": "end hash num"
    },
    {
      "node-name": "node_name",
      "start": "start hash num",
      "end": "end hash num"
    }
  ]
}
```

### Added/Leave Node

- manager node 를 통해 추가/삭제
  - manager node 로 부터 추가/삭제 관련 command 를 받음
- range 는 2영역에 걸쳐 생성될 수 있음

```
+---------------------+---------------------+---------------------+
|        node01       |        node02       |        node03       |
+---------------------+---------------------+---------------------+
|       (20, 30]      |       (30, 40]      |       (40, 50]      |
+---------------------+---------------------+---------------------+

+--------+
|NEW node|-----------------------------+ node02 split
+--------+                             |
                                       V
+---------------------+----------+----------+---------------------+
|        node01       |  node02  | NEW node |        node03       |
+---------------------+----------+----------+---------------------+
|       (20, 30]      | (30, 35] | (35, 40] |       (40, 50]      |
+---------------------+----------+----------+---------------------+

or

+--------+
|NEW node|-----------------------------+ node02 and node03 split
+--------+                             |
                                       V
+---------------------+--------------+--------------+-------------+
|        node01       |    node02    |   NEW node   |   node03    |
+---------------------+--------------+--------------+-------------+
|       (20, 30]      |   (30, 35]   |   (35, 40]   |  (40, 50]   |
+---------------------+--------------+--------------+-------------+
```

#### manifest_list file

- 노드간 manifest_list file 을 통해 노드가 가지고 있는 manifest 의 리스트를 확인할 수 있어야 함

### 일반 데이터 및 복사

- 진행 상태에 따라 일정을 조율함

---

## hash-chain

- [관련파일](https://github.com/uni2u/difs/blob/documents/meet/20210318_kickoff_hashchain.md)

### difs-cxx

- difs-cxx 의 이슈를 통해 진행되고 있음

### redesign

- 협의가 진행되어야 함
  - redesign 을 위한 overhead 가 생기지 않도록 keyspace (동적노드구성) 부분 조율이 필요함

---

### github issues 사용 권장

- 의문사항 및 진행관련 협의 사항이 발생하는 경우 사용하길 권장
  - 히스토리를 남겨 상호 이해를 높이기 위함
- 메일을 활용한 의문사항 해소
  - github 사용이 어렵거나 github 자체의 부담이 있는 경우 메일 권장
    - 단 메일 수신인에 @uni2u , @justin-labry 는 포함될 수 있도록 부탁

**Comment by uni2u** [comment]
## 동적노드구성 (KeySpace)

### 동적구성을 위한 config

- `parent: node` 부분을 `parent: {node, node}` 로 구성
  - 노드 2개에 걸친 KeySpace 생성

```json
{
  "type": "manager or node",
  "parent": {
    "left": "node_name",
    "right": "node_name"
  }
}
```

**Comment by uni2u** [comment]
## KeyValue Store 고도화

### mongoDB

- DIFS 명령어는 수정하지 않음
  - `ndnputfile {common_name} {DIFS_data_name} {file}`
  - `ndngetfile {DIFS_data_name}`

#### INC 전용 명령어 교체

- 현재 적용된 DIFS 명령어
  - `ndnputfile {common_name} {DIFS_data_name} {key} {file}` 
  - `ndngetfile {key}`
- DIFS 에서는 {key} parameter 를 사용하지 않기 때문에 원 명령어 형태로 수정 필요
  - `ndnputfile {common_name} {DIFS_data_name} {file}`
  - `ndngetfile {DIFS_data_name}`
  - {DIFS_data_name} 을 {key} 로 사용하여야 함
    - 즉, {DIFS_data_name} 에 대한 value 가 {instance_name}

#### 동작과정 및 개념

- 필요한 경우 온라인으로 1시간 정도 설명 시간을 가질 수 있도록 함

**Comment by sungho-gurumnet** [comment]
> ## KeyValue Store 고도화
> ### mongoDB
> * DIFS 명령어는 수정하지 않음
>   
>   * `ndnputfile {common_name} {DIFS_data_name} {file}`
>   * `ndngetfile {DIFS_data_name}`
> 
> #### INC 전용 명령어 교체
> * 현재 적용된 DIFS 명령어
>   
>   * `ndnputfile {common_name} {DIFS_data_name} {key} {file}`
>   * `ndngetfile {key}`
> * DIFS 에서는 {key} parameter 를 사용하지 않기 때문에 원 명령어 형태로 수정 필요
>   
>   * `ndnputfile {common_name} {DIFS_data_name} {file}`
>   * `ndngetfile {DIFS_data_name}`
>   * {DIFS_data_name} 을 {key} 로 사용하여야 함
>     
>     * 즉, {DIFS_data_name} 에 대한 value 가 {instance_name}
> 
> #### 동작과정 및 개념
> * 필요한 경우 온라인으로 1시간 정도 설명 시간을 가질 수 있도록 함

INC 에서 DIFS를 사용하는 케이스가 크게 2가지로 나눠져 있습니다.

1. save instance name
2. save result

save instance name의 경우 클라이언트에서 생성한 키를 function에 전달하여 처리한 function의 인스턴스 이름을 클라이언트에서 보내준 키를 이용하여 difs에 저장합니다.
만약에 보내주신 방식으로 data_name만을 이용할 경우 다른 function, 클라이언트에서 key만 가지고 인스턴스의 이름을 찾을 수 없게 됩니다.

save result의 경우 클라이언트에서 생성된 키를 function에 전달하여 function이 처리된 결과 값을 클라이언트가 보내준 키를 이용하여 difs에 저장합니다.
위와 마찬가지로 클라이언트와 다른 function에서는 키만 가지고 결과 값을 difs에서 찾지 못할 것 같습니다.

위 문제 해결을 위해 아래 방식처럼 적용을 하면 어떨까요?
$ ndnputfile {common_name} {DIFS_data_name} {file} -f {forwarding_hint} 

ex) INC에서 사용하는 경우
$ ndnputfile /DIFS_COMMON_NAME /KEY [data] -f /ndn/etri/hii/%C1.Region/Building0/%C1.Router/Router0/%C1.Worker/Worker0/%C1.EE/INSTANCE_NAME

이렇게 하면 포워딩 힌트를 이용하여 DIFS에서도 데이터 Producer를 찾을 수 있고, data이름도 그대로 사용할 수 있지 않을까 합니다.

필요하다면 INC와 함께 온라인 회의를 진행하면 좋을 것 같습니다.

**Comment by uni2u** [comment]
@sungho-gurumnet 

'key' 라고 하는 것이 유일한 값으로 알고 있습니다.

DIFS 에서 {DIFS_data_name} 이란 데이터 생산자가 DIFS 에 데이터를 저장하고 이 데이터를 서비스할 이름을 의미합니다.
즉, {DIFS_data_name} 은 데이터 생산자가 마음껏 지정한 이름입니다.
의미있는 이름이 포함되건, 의미없는 단어의 연결이건 상관하지 않습니다.
단, 네트워크에서 이 이름은 중복되지 않습니다. (DIFS 는 이름이 같은 경우 error 처리를 진행합니다.)
또한, 사용자는 {DIFS_data_name} 을 알고 있다는 것을 전제로 합니다. (스토리상 과제의 마켓플레이스로 부터 데이터를 구매하면 접근가능한 데이터 이름을 알려주는 것으로 되어 있습니다.)

- 예) 내 컴퓨터의 '/tmp/mv/롤린.mp4' 파일을 DIFS 에 저장하고 '/롤린-브레이브걸스' 이름으로 서비스 한다면
  - 'ndnputfile /etri/difs /롤린-브레이브걸스 /tmp/mv/롤린.mp4' 처럼 저장합니다.
    - {common_name}: /etri/difs
    - {DIFS_data_name}: /롤린-브레이브걸스 (DIFS 에서 이 이름은 중복되지 않으며 유일한 이름; 데이터 생산자가 정하는 이름)
    - {file}: /tmp/mv/롤린.mp4

INC 파트에서 DIFS 파트와 초기 협의를 할 때 {DIFS_data_name} 자리에 key 를 사용하는 것으로 모델링 하였습니다.

하여 아래와 같은 루틴을 가지는 것으로 진행되었습니다. 

- save instance name
  - 인스턴스는 자신의 이름 (/xxx/xxx 형식) 을 파일로 작성하고
  - 네트워크에서 유일한 key (인스턴스 ID?) 를 파악한 뒤
  - DIFS 에 다음과 같이 저장
    - 'ndnputfile {DIFS_common_name} {InstanceID} {Instance_Name file}'
    - 다른 인스턴스가 저장된 내용을 가지고 오는 경우
    - 'ndngetfile {InstanceID}'

ForwardingHint 이전에 {DIFS_data_name} 과 {key} 의 관계를 다시 한번 생각해봐야 할 듯 합니다.

들어주신 예에서...

- 클라이언트에서 생성한 key 를 function 에 전달하여 처리한 function 의 인스턴스 이름을 클라이언트에서 보내준 키를 이용하여 DIFS 에 저장
  - 'ndnputfile {DIFS_common_name} {key} {instanceName_file}'

로 가능하지 않나요?

다만, 현재의 버전은 value 값이 String 이 아닌 파일로 저장되어야 하기 때문에 이에 대한 요구가 있었습니다.

추후 mongoDB 를 사용하게 되면 String 타입의 value 를 제공할 수 있을 것으로 예상하고 있습니다.

**Comment by sungho-gurumnet** [comment]
difs 노드와 ndnputfile을 하는 노드가 동일할 경우 말씀해주신 방법으로도 충분할 것 같습니다.

그러나 difs노드와 클라이언트(ndnputfile) 노드가 다른 노드의 경우 difs노드에서 클라이언트 노드까지 요청이 전달 될 수 있도록 라우팅 추가가 필요합니다.
기존의 경우 데이터 이름을 가지고 difs 노드에서 클라이언트 노드까지 라우팅을 추가해서 사용한 것으로 알고 있으나, INC의 경우 저장하고자 하는 key(DIFS_data_name)와 인스턴스(data를 제공해주는 노드)의 이름이 서로 다르다보니 인스턴스까지 요청이 전달 될 수 있도록 하기 위해서는 ndnputfile에 Forwarding hint 옵션을 추가하여 DIFS 노드에서 인스턴스까지 요청 전달시 사용할 수 있도록 해야 하지 않을까 합니다.

**Comment by uni2u** [comment]
@sungho-gurumnet 

어떤 부분인지 이해했습니다.
최초 인스턴스가 DIFS 에 저장을 요청하면 실제는  DIFS 에서 해당 인스턴스로 데이터를 가지고 오기 위한 Interest 를 보내고 인스턴스에서 데이터를 주는 과정에 대한 의문인 것이지요?

실제 이 과정은 repo-ng 의 command flow 를 그대로 사용하고 있습니다.

우리가 ndnputfile 을 사용하면 다음과 같이 정의 됩니다.

`/etri/difs/insert/<RepoCommandParameter>/<timestamp>/<random-value>/<SignatureInfo>/<SignatureValue>`

- /etri/difs: {DIFS_common_name}
- insert: insert 를 지칭
- RepoCommandParameter
  - Name: 가져올 데이터의 이름
  - StartBlockId: segment 시작
  - EndBlockId: segment 끝
  - ProcessId: insert/delete 프로세스
  - InterestLifetime: 전송한 Interest 에 대한 수신 데이터 대기 시간 (optional)
  - ForwardingHint: Forwarding Hint (default: false)

위 Interest 를 받은 DIFS 는

- RepoCommandParameter 를 확인하여 Interest 생성
- `/Name(data prefix)/StartBlockId`

를 보내는 것으로 알고 있습니다.

즉, RepoCommandParameter 의 Name 필드를 사용하면 될 것으로 보이는데 가능한지 다시 체크해보겠습니다.

**Comment by sungho-gurumnet** [comment]
네 맞습니다 ㅎㅎ

Name 필드가 DataName, DataProducerName으로 나누어지고,
DIFS에서는 Data요청시 DataProducerName을 Forwarding Hint로 사용하여 DataName에 해당하는 데이터를 요청하면 되지 않을까 합니다.

**Comment by uni2u** [comment]
@sungho-gurumnet 

현재 DIFS 에서 log 를 출력해본 결과 다음과 같습니다.

producer 에서  ndnputfile {DIFS_common_name} {DIFS_data_name} {file} 로 저장요청을 하면

producer 는  {DIFS_data_name} 으로 advertise 합니다.

DIFS 는 `/{DIFS_data_name}/segment` 형태로  _Interest_ 를 전송하며

producer 는 이에대한 Data 로 응답합니다.

**Comment by uni2u** [comment]
@sungho-gurumnet 

위 내용은 로컬노드에서 사용시의 log 입니다.

로컬노드이다 보니 init 하면서 노드 name, 공통 name 을 미리 등록하기에 가능한 일 입니다.
(즉, DIFS config 에 적용된 node name 을 사용하여 DIFS 동작시에 이미 advertise 되어 있기 때문에 가능한 내용입니다.)

다른 표현으로 register prefix 등록을 하기 때문에 가능합니다.
(위 글에 표현한 advertise 의 의미는 registerprefix 등록의 의미 입니다. 적절한 단어가 생각나지 않아 advertise 라는 단어를 사용했습니다. 혼란을 드려 죄송합니다.)

registerprefix 설명은 다음을 참고하시면 되겠습니다. (https://named-data.net/doc/ndn-cxx/current/doxygen/d9/d55/classndn_1_1Face.html#a30d082dcdc0f96e93de243566aa1962f)

- registerprefix
  - 연결된 NDN forwarder 에 prefix 를 등록
  - Forwarder 의  RIB 만 수정하며 onInterest callback 에 연결하지 않음
  - setInterestFilter 메서드를 사용하여 incoming Interest 를 올바른 callback 으로 dispatch

위 내용에서의 핵심 사항은 DIFS 는 producer 에게 `/{DIFS_data_name}` 을 사용하여 _Interest_ 를 전송한다는 점 입니다.

추후 ndnputfile 관련 library 를 만들때 해당 내용이 반영될 수 있도록 하여야 할 듯 합니다.

**Comment by uni2u** [comment]
@sungho-gurumnet 

- DIFS command 체계 고도화 관련하여 위 내용이 포함될 수 있도록 함
- `/{DIFS_common_name}/insert`
  - **RepoCommandParameter**
    - `name`: DIFS_data_name 을 의미함
    - `start_block_id` (optional): segment 시작 번호
    - `end_block_id` (optional): segment 끝 번호
    - `forwarding_hint` (optional): forwarding hint 를 통한 data fetching
      - 현재 DIFS 는 RepoCommandParameter 를 사용하지 않는  forwarding hint 적용
      - 관련하여 repo-ng 에도 reference 가 없는 관계로 ndn-python-repo 내용을 참고하여 수정 필요
    - `register_prefix` (optional): DIFS 의 root prefix 가 없는 경우 클라이언트에서 prefix 등록
    - `check_prefix`: Interest 관련 status 체크
    - `process_id`: insert process 를 나타내는 random value
    - `cluster_id` (DIFS 단독): 클러스터 id
    - `node_prefix` (DIFS 단독; optional): **INC node prefix**
