### ISSUE TITLE
Interest 겹치는 문제

### ISSUE THREAD

**Issue by tribela** [uni2u/difs#3]
put을 할 때 Storage에서 Producer쪽으로 매니페스트를 받기 위해 요청하는 인터레스트는 별다른 명령 없이 데이터 네임 그 자체입니다. 이 때는 저장소에 대한 정보를 가지고 있지 않은 기본적인 내용만 담은 매니페스트입니다.
![image](https://user-images.githubusercontent.com/5047683/66988498-98a73d80-f0fd-11e9-85b9-3b3e7696a0b1.png)

get을 할 때 Consumer가 매니페스트를 얻기 위해 보내는 인터레스트도 별다른 오퍼레이터 없이 데이터 네임 그대로입니다. 그림에서 Storage2가 Name을 해싱하여 Storage4에서 매니페스트를 받아 오도록 설계가 되었지만 실제로는 Put 할 당시의 기본 매니페스트가 동일한 이름을 가진 채 캐시에 남아 저장소 정보가 없는 기본 매니페스트를 받아오게 됩니다.
![image](https://user-images.githubusercontent.com/5047683/66988639-d906bb80-f0fd-11e9-88ed-aebbf46a0868.png)

이를 해결하기 위해서는 Consumer에서 애초에 해싱 된 결과를 가지고 매니페스트를 따로 요청해야 할 것 같습니다.

**Comment by uni2u** [comment]
이슈에 대한 내용은 공감합니다.

두가지 방법이 있는 듯 합니다.

- cache time 설정
  - 이렇게 하면 Producer 에서 제공하는 manifest 에 대한 부분만 caching time 을 줄일 수 있을 듯
  - [Local Cache Policy](https://redmine.named-data.net/projects/nfd/wiki/NDNLPv2) 에서 CachePolicyType 를 'NoCache' 로 설정하는 방법
- Consumer 에서 해싱결과로 manifest 요청
  - 이렇게 하면 interest: .../.../{content_name hashing} 로 요청
  - 요청을 받은 storage 는 hashing 번호를 보고 manifest storage 검색

고민은 해보겠지만 일단은 아름씨가 제안한 방법이 가장 간단한 듯 합니다.

**Consumer 에서 해싱 결과로 manifest 요청** 하는 방법으로 처리하는 방안으로 결정
