### ISSUE TITLE
mongodb 구성 체크

### ISSUE THREAD

**Issue by uni2u** [uni2u/difs#30]
### nosql 적용

- mongodb 적용
  - commit: https://github.com/uni2u/difs/commit/ae1cfafec74f18e6836b0945f0db554a2680c73e
    - @uni2u 체크 예정

**Comment by uni2u** [comment]
@yul-gurum 님 위 commit 내용이 싱글 노드에서 mongodb 적용인가요?
(지난 kick-off 에서 설명하신 내용)

**Comment by yul-gurum** [comment]
@uni2u 네. 참고로 kick-off 이전에 작업했던 것이라 kick-off 이후의 내용들은 아직 반영되지 않은 것입니다.

**Comment by uni2u** [comment]
@yul-gurum 잘알겠습니다. 수고하셨습니다. 감사합니다.

**Comment by uni2u** [comment]
## Tools

### ndnputfile

- `ndnputfile <option> {DIFS_common_name} {DIFS_data_name} {file}`
  - 현재 option 으로 예약된 내용
    - `-u`: unversioned: do not add a version component
    - `-s`: single: do not add version or segment component, implies -u
    - `-D`: use DigestSha256 signing method instead of SignatureSha256WithRsa
    - `-i`: specify identity used for signing Data
    - `-I`: specify identity used for signing commands
    - `-x`: FreshnessPeriod in milliseconds
    - `-l`: InterestLifetime in milliseconds for each command
    - `-w`: timeout in milliseconds for whole process (default unlimited)
    - `-v`: be verbose
  - ex) ndnputfile -D /etri/difs  /rollin  /music/bg/rollin.mp4 (DigestSha256 signing)
- forwarding_hint 또는 node_prefix 관련 option 은 아직 결정되지 않음
  - option 으로 적용시 예약된 option 은 사용하지 않아야 함
    - 예) `-f`: forwarding_hint (ndnputfile -f /gurum/node01  /etri/difs  /rollin  /music/bg/rollin.mp4)
    - 예) `-n`: node_prefix (ndnputfile -n /gurum/node01  /etri/difs  /rollin  /music/bg/rollin.mp4)

---

- ndnputfile 관련 수정은 **command 체계 고도화** 관련 작업이 진행된 후 진행
- user tool lib 관련하여 ndnputfile 이 필요한지 고찰필요
  - `/{DIFS_common_name}/insert`
    - **RepoCommandParameter**
      - `name`: DIFS_data_name 을 의미함
      - `start_block_id` (optional): segment 시작 번호
      - `end_block_id` (optional): segment 끝 번호
      - `forwarding_hint` (optional): forwarding hint 를 통한 data fetching
        - 현재 DIFS 는 RepoCommandParameter 를 사용하지 않는  forwarding hint 적용
        - 관련하여 repo-ng 에도 reference 가 없는 관계로 ndn-python-repo 내용을 참고하여 수정 필요
      - `register_prefix` (optional): DIFS 의 root prefix 가 없는 경우 클라이언트에서 prefix 등록
      - `check_prefix`: Interest 관련 status 체크
      - `process_id`: insert process 를 나타내는 random value
      - `cluster_id` (DIFS 단독): 클러스터 id
      - `node_prefix` (DIFS 단독; optional): **INC node prefix**
