### ISSUE TITLE
노드 정보 모니터링

### ISSUE THREAD

**Issue by uni2u** [uni2u/difs#34]
### 모니터링

- DIFS 노드의 리소스 정보를 제공

### Overview

- dashboard 에서 선택된 노드의 정보 제공
  - `ndn://{node_name}/nodeinfo`
    - {node_name}: keyspace 데이터 확인
      - keyspace 는 동적 노드 구성을 진행하면서 생성됨
      - 즉, manager 노드로 부터 제공받은 keyspace 파일에 각 노드의 _{node_name}_ 이 있음
      - dashboard 는 _{node_name}_ 을 확인하고 요청 _Interest_ 를 전송
- 응답 데이터: JSON 형식의 파일

```json
{
  "name": "node_name",
  "disk": {
    "size": "total_size",
    "usage": "usage"
  },
  "memory": {
    "size": "total_size",
    "usage": "usage"
  },
  "manifests": [
    {
      "key": "manifest_name"
    },
    {
      "key": "manifest_name"
    }
  ],
  "datas": [
    {
      "data": "data_name"
    },
    {
      "data": "data_name"
    }
  ]
}
```

### 리소스

- DISK (디스크 정보)
  - total size
  - usage
- MEMORY (메모리 정보)
  - total size
  - usage
- MANIFESTS
  - manifest file list
- DATAS
  - data list

**Comment by uni2u** [comment]
- 리소스 정보
  - 수집이 어려운 경우 알려주세요
- mongoDB 를 사용중이기에
  - 어려운 경우 저에게 알려주시기 바랍니다

- if) 실제 파일이 없어도 리소스 제공에 문제가 없다면
  - 정의된 Interest 및 json 더미 파일을 사용합니다.

**Comment by taewoong0627** [comment]
### **리소스 관련 질문**

아래와 같이 disk, memory 리소스 정보 수집에 대하여 궁금한 부분이 있어 이슈를 남깁니다.
fileSystem 인 경우 : 시스템 리소스
mongoDB 인 경우 : mongoDB resource
를 사용하는 것인가요? 아니면 둘 다 시스템 리소스를 사용하는것인지 말씀해주시면 감사하겠습니다.

```
  "disk": {
    "size": "total_size",
    "usage": "usage"
  },
  "memory": {
    "size": "total_size",
    "usage": "usage"
  },
```

**Comment by uni2u** [comment]
- 시스템 리소스를 의미합니다.
  - 만약 리소스 관련 수집이 어렵다면 mongoDB 리소스를 하여도 무방합니다.
    - mongoDB 는 관련 API 가 있는 것으로 알고 있습니다.

**Comment by uni2u** [comment]
- 관련 기능 확인함
