### ISSUE TITLE
Get 요청 관련 이슈

### ISSUE THREAD

**Issue by taewoong0627** [uni2u/difs#48]
Get 요청시에 발생하는 hc-segment-fetcher 에 관련된 이슈입니다.

**Get HashChain 반복 문제**

문제 원인은 아래와 같습니다.

- put 할 때 DIFS 에서 받은 데이터를 새로운 이름(저장되는 노드 이름)으로 다시 데이터를 생성 후 저장
  => data를 새로 만들어 sign 후에 저장하기 때문에 다시 hash-chain을 적용 해야함
  => 이 과정에서 소요되는 시간 증가 및 타임아웃 문제 발생(hash-chain은 맨 뒤부터 sign을 해야하기 때문)
- get 요청시
  => 마지막 데이터 요청이 들어올 때 까지 데이터를 주고 받을 수 없게 됨
  => 데이터의 사이즈가 커질 수록 소요시간 증가 + 타임아웃 문제 발생

위와 같은 문제가 있습니다. 이 부분의 해결 방법에 대해서는 현재 2가지 방법이 나왔습니다.

그 방법은 다음과 같습니다.

1. Forwarding Hint 사용 => 적용이 가능한지 파악 불가능
 현재는 데이터를 노드의 이름 ex) /seoul/difs/data/{data_name}/ 으로 저장되어, Forwarding Hint 없이
데이터를 가져올 수 있습니다. 하지만 이름을 다시 만들지 않고 그대로 저장하고, 요청을 보내는 쪽에서
Forwarding Hint 를 적용하여 요청을 보내는 방식입니다. 이 부분은 Forwarding Hint 관련하여 적용 및 
확인이 필요합니다.

2. HashChain 매커니즘 수정
 현재 hash-chain은 다음과 같이 동작합니다.
 - 데이터를 뒤에서 부터 읽어와 sign 진행 후 nextHash block 생성
   => 이 과정에서 데이터를 뒤에서 부터 읽어 파일의 위치 이동 및 반복 작업 발생
 - 데이터를 보내 다음 데이터가 도착시에 만들어 놓은 nextHash block 을 이용해 검증 진행

    수정 후 동작 방식(put 일 경우에만 적용)
  - 데이터를 앞에서 부터 차례대로 sign 진행
    => 뒤에서 부터 진행하던 구조를 앞에서부터 차례대로 진행
  - put 할 때 데이터를 뒤에서 부터 보냄(이 부분은 글로 설명이 힘들어서, 혹시 이해가 안되시면 말씀해주세요!)
    => RepoCommandParameter 사용(보내는 데이터의 실제 순서)
    => 예를 들어 /data/{data_name}/0 번 요청이 왔을 때 실제로는 마지막 데이터를 먼저 보냄
    => 데이터를 받는 write-handle 쪽에서 RepoCommandParameter 에 저장 된 실제 데이터의 순서를
         가져와 데이터를 다시 생성(원래 데이터의 이름으로)
    => sign 후 저장(실제 데이터는 끝에서 부터 왔기때문에 기존 hash-chain 과 동일)
    => get 을 하게 되면 기존 hash-chain과 동일하게 검증가능

혹시 또 다른 의견이나 더 좋은 방법이 있으시면 말씀해주시면 확인하겠습니다.

**Comment by uni2u** [comment]
### 1. ForwardingHint 관련
- 당연히 적용되어야 할 부분 입니다.
- INC 를 위한 NODE_PREFIX 부분이 ForwardingHint 와 비슷하게 동작합니다.
- 참고해서 FORWARDING_HINT 를 구성하면 될 듯 합니다.

**Comment by taewoong0627** [comment]
### ForwardingHint 관련

ForwardingHint 관련되어 궁금한 부분이 있어서 말씀드립니다.

현재 간단한 예제를 통해 ForwardingHint 로 구성을 할 수 있다는 것은 확인하였습니다.

적용하는 부분은 작업을 해야하는데, 작업하기 전에 우선 저희가 생각하는 방법은 다음과 같습니다.

1. data가 저장되는 노드에 data_name 으로 filter 를 등록한다.
2. get 요청을 통해 manifest 를 가져와 data를 fetch 해올 때 data가 저장된 노드의 이름을
    ForwardingHint 세팅하여 요청을 보낸다.

제가 팀장님께 들은걸로는 새로 만들어진 NFD? 가 node-name 으로 각각 thread 를 돌린다고 알고 있습니다.
하지만 위에있는 ForwradingHint 방식은 node-name 으로 요청을 보내는게 아닌 node-name 을 ForwardingHint 로 세팅하여 보내는 방식이라 새로 적용되는 NFD 가 의미가 없어질수도 있을것 같습니다.

혹시 생각하시는 ForwardingHint 적용이 저희가 생각하는 방식과 다른 방법인지 위와 같은 새로운 NFD를 사용할 경우에 발생할 수 있는 성능문제에 대해 어떻게 생각하시는지 말씀해주시면 감사하겠습니다.

**Comment by uni2u** [comment]
## CASE 1) 생산자가 데이터 저장 요청을 ForwardingHint 를 통해서 요청할 때
- 이 경우는 요청 받은 저장소가 무조건 데이터를 저장하기 때문에 node-name 에 따른 thread 가 필요 없습니다.
- INC 연동에 사용할 NODE-PREFIX 와 동일하게 동작하면 될 듯 합니다.

## CASE 2) 소비자가 데이터를 요청할 때
- manifest 를 받은 소비자가 manifest 에 표기된 노드 이름을 ForwardingHint 로 적용하여 저장소의 데이터를 요청하게 됩니다.
- 이 경우 라우터를 지나가면서 node-name 에 따른 thread 가 적용되는 것으로 알고 있습니다.

CASE 1 은 생산자가 ndnputfile 하면 DIFS 가 생산자 쪽으로 Interest 를 보내어 데이터를 저장하는데 ForwardingHint 를 사용하는 의미이며, CASE 2 는 소비자가 ndngetfile 하면 DIFS 에서 제공하는 manifest 를 보고 node-name 을 ForwardingHint 에 담아 DIFS 노드로 보내는 의미입니다.

---

## MW-NFD 란
MW-NFD 는 node-name 마다 thread 를 적용하여 동시 요청을 수용할 수 있도록 하는 모델로서 간략히 설명하자면 라우팅 테이블 (RIB) 에 대한 thread 로 설명들었습니다.

- 즉, 리전이 3개 /seoul, /busan, /jeju 가 있고 각 리전마다 MW-NFD 가 동작한다고 가정하면
  - /seoul 리전의 MW-NFD thread 는 /busan, /jeju 2개가 생성됩니다.
  - 하여 /busan, /jeju 로 향하는 패킷의 처리를 각 thread 로 동시에 처리할 수 있도록 하게 됩니다.
- DIFS 의 경우 MW-NFD 가 동작하는 서버에 하나씩 설치가 되고 이름은 각각 /seoul/difs, /busan/difs, /jeju/difs 가 됩니다.
  - /seoul 리전을 다시 예로 들자면 /busan/difs 로 향하는 패킷의 처리는 /busan thread 가 처리하고
  - 동시에 /jeju/difs 로 향하는 패킷의 처리는 /jeju thread 가 처리하는 구조가 됩니다.

**Comment by taewoong0627** [comment]
### **Forwarding Hint 적용 후 변경된 부분**

1. 기존 데이터를 저장하는 방식은 {node-name} 을 추가하여 데이터를 다시 생성해 저장하였던 부분을, 요청 된 {data-name} 그대로 저장하도록 수정하였습니다.
2. 기존에는 데이터를 저장하게되면 {node-name}/{data-name} 으로 라우터를 추가하도록 되어있었습니다. 이 부분을 / 로 라우터를 등록하여 처리하도록 수정하였습니다. 이 부분 같은경우에는 {data-name} 으로 라우터를 다 추가하도록 진행하려고 하였으나, 데이터를 많이 저장할수록 라우터의 개수가 늘어나는 문제가있어 / 로 통일하여 테스트를 진행해보고 우선 적용시켰습니다.
3. 클라이언트에서 데이터를 요청할 때 {node-name} 을 앞에 붙여 요청을 보냈는데, 수정 후에는 {node-name} 을 forwardingHint 로 넣어 보내게됩니다.

2번 같은 경우에는 우선 추가되는 라우터의 개수를 최대한 줄이기 위하여 / 로 테스트를 진행해보고 적용시켰지만, 혹시나 다른 방법 또는 / 를 사용하지 않으실 예정이라면, 말씀해주시면 확인하고 수정하도록 하겠습니다.

**Comment by uni2u** [comment]
- ForwardingHint 적용에 대한 기능 동작을 확인함
- 라우팅 테이블 '/' 를 통한 전체 트래픽의 경로를 설정하는 것은 타당한 것으로 판단함

**Comment by uni2u** [comment]
- ForwardingHint 구현 확인
- '/' 를 통한 라우팅 패스 적용 확인
- get 관련한 성능은 'mongodb collection' 이슈를 통하여 논의
  - collection 을 단일 {data} 에서 각 {data name} 으로 생성
