### ISSUE TITLE
delete interest naming

### ISSUE THREAD

**Issue by tribela** [uni2u/difs#5]
파일을 삭제하기 위해서는 Manifest, Data가 둘 다 삭제 되어야 합니다. 이를 위해 다음과 같은 네이밍을 제안합니다.

(PascalCase = 변수, camelCase = 상수)
| RepoName | desc |
|--|--|
repo0 | 클라이언트의 명령을 받은 저장소
repo1 | 매니페스트를 가지고 있는 저장소
repo2 | 실제 데이터를 가지고 있는 저장소

- `/Repo/delete/Name` - Name에 대한 데이터 삭제 client to repo0
- `/Repo/Id/deleteManifest/Name` - Name에 대한 Manifest 삭제 - repo0 to repo1
- `/Repo/Id/deleteData/Name` - Name에 대한 Data삭제 - repo1 to repo2

폴더를 삭제할 때 하위 항목부터 삭제한 후 상위 항목을 삭제하는 것처럼 요청은 client - repo0 - repo1 - repo2 순으로 전달되며 삭제는 그 역으로 Data, Manifest 순서로 삭제되도록 할까 합니다.
repo2는 데이터를 삭제한 후 OK를 보내고 repo1은 그 OK사인을 받은 직후 Manifest를 삭제한 후 repo0에게 OK를 보내며 최종적으로 repo0이 OK사인을 클라이언트에게 전달하는 방식입니다.

이렇게 설계한 이유는 굳이 매니페스트 파일을 클라이언트가 받아 볼 필요 없이 **요청을 받은 레포는 매니페스트가 어디 있는지 알고** 있으며, **매니페스트를 가진 레포는 데이터가 어디 있는지 알기** 때문입니다.

```
client                                repo0                                    repo1                                 repo2
    |-------/repo/delete/(data/1)------>|                                        |                                     |
    |                                   |-----/repo/1/deleteManifest/(data/1)--->|                                     |
    |                                   |                                        |-----/repo/2/deleteData/(data/1)---->|
    |                                   |                                        |                                     |
    |                                   |                                        |                                     |
    |                                   |                                        |                                     |
    |                                   |                                        |<--------------O-K-------------------|
    |                                   |<---------------O-K---------------------|                                     |
    |<----------O-K---------------------|                                        |                                     |
    |                                   |                                        |                                     |
    |                                   |                                        |                                     |
    |                                   |                                        |                                     |
    |                                   |                                        |                                     |
    |                                   |                                        |                                     |
    |                                   |                                        |                                     |
```

**Comment by uni2u** [comment]
의견 감사합니다.

delete 관련한 Flow 에서 반드시 필요한 부분이며 이에대한 좋은 의견이라 생각됩니다.

제안하신 naming 및 메커니즘을 적용하는 것으로 정리하겠습니다.

감사합니다.

다만 다음의 내용도 넓게는 생각하여야 합니다.

- 동일 데이터가 카피가 되어 repo2(원본)/repo4(카피) 에 위치하는 경우
- manifest 담당 repo1 에는 repo2 및 repo4 의 prefix 가 만들어지고
- 이 중 repo2 의 데이터만 삭제하는 경우가 발생하면
- repo1 의 manifest 는 repo2 의 prefix 만 삭제

즉, manifest update 관련 내용입니다.

단!! manifest update 는 우선순위가 낮기 때문에 지금 고민할 내용은 아닙니다.

**Comment by uni2u** [comment]
```
2020.06.22. 13:26

NDN-CXX 0.7.0 버전을 사용하는 repo-ng 최근 버전에 DIFS를 포팅 완료하였습니다.
repo-ng의 버그를 확인하던 중 ndn-cxx의 수정이 불가피하여 ndn-cxx의 일부분을 수정하였습니다.
변경사항은 첨부파일로 보내드립니다.

새로 포팅 된 difs버전은 difs 브랜치로 푸시 하였습니다.
```

- 체크 중
- difs branch (https://github.com/uni2u/difs/tree/difs)
- ndn-cxx-0.7.0 수정 적용 후 install
  - 첨부 zip file unzip 후 .patch 활용
  - git apply {file.patch}
- insert/get/delete 체크

[bugfix.patch.zip](https://github.com/uni2u/difs/files/4811415/bugfix.patch.zip)

**Comment by uni2u** [comment]
### delete

- ndndelfile: 없는 data_name 을 요청하는 경우
  - 'segmentation fault' 발생
  - DISF system 멈춤

- 해결방안
  - exception: warning 발생 `{data_name} not found`
  - DIFS 가 멈추지 않도록 함
