### ISSUE TITLE
성능개선 - mongodb insert

### ISSUE THREAD

**Issue by uni2u** [uni2u/difs#50]
### mongodb data insert
- segment 가 많이 생성된 경우 mongodb insert 과정이 느림
  - `fallocate -l 64M /tmp/64m.txt` 를 통해 64M 크기의 데이터 생성
  - 8,800 byte 사이즈로 나뉘는 경우 segment 는 7,200 여개 생성
  - 7,200 여개의 segment 를 mongodb 에 insert 하는 과정

#### 대응방안
- 현재 `db.collection.replaceOne()` 을 사용하고 있음
  - 대체1) `db.collection.bulkWrite()`
  - 대체2) `db.collection.insertMany()`
  - 대체3) 그외 방법

**Comment by uni2u** [comment]
- 대체1), 대체2) 방안은 인터넷 검색 결과이기 때문에 우리 모델에 적용이 어려울 수 있음
  - 또한, insert 성능이 좋아진다는 보장은 없음
- 다른 좋은 방안이 있다면 제안해주세요.
  - mongodb 가 read/write 가 매우 좋다고 했는데...

**Comment by sungho-gurumnet** [comment]
현재 data write 같은 경우는 데이터 이름(name + segment_id)의 해시 값을 key로 사용하여 저장을 하고 있습니다.
그러다보니 데이터를 read 하는 과정에서 각 세그먼트들을 해시 값으로 탐색하여 하나씩 읽고 있는데, 이 부분에서 select를 적용할 수 있도록 name을 추가해보는게 어떨까 합니다.

select로 데이터들을 한번에 쿼리하여 읽을 수 있다면 좀 빨라질수도 있지 않을까요?
물론... 한번에 읽어오면 데이터를 메모리에 올려놓아야 하는 만큼 데이터를 요청하는 과정에서 별도의 과정이 추가되어야 할수도 있을것 같습니다.

**Comment by uni2u** [comment]
@sungho-gurumnet 음... ndngetfile (read) 요청은 그럴 수 있겠네요... ndnputfile (insert) 의 경우는 좀 더 찾아봐야 할 듯 합니다.

**Comment by taewoong0627** [comment]
**MongoDB Insert 관련 정리**

insert 관련하여 의견을 주신 부분들을 하나씩 확인해본 결과입니다.

우선 bulk_write는 mongocxx document 와 mongocxx include 를 확인해본 결과 insert_many에서 같이 사용하고 있는것으로 판단이 되어서, insert_many로만 진행하였습니다.

테스트 진행 방식은 64, 128, 256, 512, 1024, 2048, 4096, 8192개의 chunk data 를 메모리에 저장한 후에 한 번에 insert 하는 것으로 하였고, 추가적으로 filesystem read cache 를 지우고 진행하였습니다. (File Size 64M)

테스트 결과는 다음과 같습니다.

```
64, 128, 256, 512, 1024, 2048 => 36~38초
4096 => 약 20초
8192 => 약 3초
```
하지만 위 결과값에는 문제가 있습니다. 우선 64M 데이터는 약 7760개의 chunk 가 만들어집니다.
발생하는 문제는 다음과 같습니다.

1. insert_many 함수 호출 후 segment_fetcher 의 동작이 느려짐 => 원인 파악 불가능
2. 8192 chunk size 로 테스트를 진행 시 put이 굉장히 빠르게 끝나지만 바로 get을 하게되면 중간중간 timeout 이 발생함 => 이 부분은 신기하게 데이터가 다 가져와집니다. (mongoDB 를 깨끗하게 지운 후 테스트 진행)
3. 64M 파일을 put 한 후 ndn-repo-ng 를 종료하지 않고 다른 name 으로 128M 파일을 put 한 경우 => 위에 말씀드린 것처럼 segment_fetcher 의 동작이 느려져 속도 원상복구

3번 같은 경우에는 2번의 경우일 때 영향을 받습니다. 처음 put한 데이터는 굉장히 빠르게 insert 가 되지만 다음 데이터를 바로 put하게 될 경우 이 전보다 더 느리게 insert 된다고 생각하시면 될 것 같습니다.

현재 원인은 찾지 못하였습니다. insert_many 를 호출하고 나면 갑자기 segment_fetcher 의 동작이 느려지는 현상으로 인해 고민중입니다..

**Comment by uni2u** [comment]
의견 및 테스트 공유 감사합니다. 관련 내용은 저도 같이 고민해 보겠습니다.
편하고자 사용한 mongodb 가 오히려 발목을 잡는 듯 하여 당황스럽긴 하네요.
ndn-python-repo 의 bulk insert handler 부터 고민해야 되는가 싶기도 하고...
저도 mongodb 를 간단한 용도로만 사용하였기에 고민이 많이 됩니다.
mongodb insert per second 등의 검색어로 구글링도 하고 합니다만 고민의 시간이 필요할 듯 합니다.

ndnputfile 시 hc-segment-fetcher 를 사용하여 검증하고 저장하는 단계가
- 혹시라도, ndnputfile - 저장 (fs or mongo) - verification 이라면?

분명히 메모리에 대한 글을 보았는데 찾지 못하였음
- 예를들어 64M 데이터 insert 를 처리하는데 메모리를 64M 만큼 사용했다면
- 저장 후 메모리가 클리어 되는데
- 이후 들어온 insert 가 클리어 된 64M 보다 큰 경우 클리어된 64M + 추가 크기를 가지는 것이 아니고
- 완전 새로운 파일 크기만큼 메모리를 할당하기 때문에 문제가 된다는 글이었음

[도움이 될 만한 사이트]

- https://rastalion.me/mongodb%EC%9D%98-wiredtiger-%EC%8A%A4%ED%86%A0%EB%A6%AC%EC%A7%80-%EC%97%94%EC%A7%84/
- https://elky84.github.io/2018/09/26/mongodb_architecture/
- https://deview.kr/2019/schedule/298
- write concern (https://docs.mongodb.com/manual/reference/write-concern/ , http://mongodb.citsoft.net/?page_id=10)
- 생각보다 성능이 좋지 않은듯 (https://www.arangodb.com/2018/02/nosql-performance-benchmark-2018-mongodb-postgresql-orientdb-neo4j-arangodb/)
- https://yubylab.tistory.com/entry/2-3-CRUD-Write4?category=548378

**Comment by taewoong0627** [comment]
**MongoDB collection 관련 정리 내용**

어제 MongoDB 관련된 자료 및 방법을 조사하다가 나온 결과입니다.

```
int64_t
MongoDBStorage::insert(const Data& data)
{
  uint64_t finalBlockId = data.getFinalBlock().value().toSegment();
  uint64_t segmentNo = data.getName().get(-1).toSegment();
  
  mongocxx::collection coll = mDB[COLLNAME_DATA];
  string key = sha1Hash(data.getName().toUri());

  bsoncxx::types::b_binary dataBinary;
  dataBinary.bytes = data.wireEncode().wire();
  dataBinary.size = data.wireEncode().size();

  bsoncxx::document::view_or_value replacement = document{}
    << FIELDNAME_KEY << key
    << FIELDNAME_VALUE << dataBinary
    << finalize;

  dataList.push_back(replacement);
  if(dataList.size() == 8096 || finalBlockId == segmentNo) {
    coll.insert_many(dataList);
    dataList.clear();
  } 

  auto id = hash(data.getName().toUri());
  return id;
}
```
위 코드는 현재 mongoDB  에서 insert 를 할 때 사용 하는 코드입니다. 7번째 라인을 보시면 mDB[COLLNAME_DATA] 에 접근을하여 collection 을 가져온 후 해당 collection에 insert 하는 것을 확인하실 수 있습니다.

현재 발견된 현상으로는 mongoDB의 insert 함수를
호출하게 되면 약 3000~4000개의 chunk 가 저장된 다음부터는 급격하게 느려지는 현상이 있습니다.
=> 한 collection에 데이터가 많이 쌓일수록 느려짐
=> 첫 번째 insertMany 만 빠르게 동작한다는 것을 의미함 (코드상으로는 8096 이후)

위와 같은 방법에서 고민하면서 생각한 방법과, 적용하였을 때 테스트 결과를 말씀해드리겠습니다.
1. mongoDB의 collection name을 data.name 으로 하여 각 collection(데이터 이름별로) 저장
1번과 같은 방법으로 테스트를 하게되면 코드는 다음과 같이 변하게됩니다.
```
mongocxx::collection coll = mDB[data.getName().toUri()];
* data_name은 뒤에 segment number 를 제외한 /difs/0000 식으로만 저장
* 위 코드는 예시용으로 작성됨
```
위의 방법으로 테스트를 한 결과는 fs 와 비슷한 시간이 걸리는 것을 확인하였습니다.
다만 저 방법을 사용하게 된다면 문제점이 있습니다. 

들어오는 데이터들을 모두다 메모리에 올려놓은후 chunk size단위로 저장하는 것이아닌
finalBlockId == semgnetNo 으로 확인을하여 한번에 다 insert를 하여야 된다는 점입니다.
=> 메모리 사용량이 늘어남

또한 생성되는 table의 개수가 늘어납니다
=> 데이터 이름으로 저장하기때문에 새로운 데이터 이름이 들어오게 되면 table이 추가됨(현재는 data table 하나만 사용)

2. mongoDB 코드 중 성능저하가 일어나는 곳
이 부분은 확인해본결과, mongoDB의 insert가 느려지거나 접근이 느려지는것은 아니었습니다. mongoDB에 특정 개수 이상의 chunk를 insert한 다음부터 segmentFetcher의 동작이 비정상적으로 느려지는 것으로 확인하였습니다.
=> SegmentFetcher의 성능이 저하되는 원인 파악 불가능

예를 들어 8096개의 chunk를 저장한다음 다음 데이터를 put 하게되면 segmentFetcher가 비정상적으로 느려져 등록해놓은 onDataValidation 함수 호출이 느려집니다.

그래서 결과는 다음과 같습니다.
1. DB collection table을 데이터 네임별로 나눈다.
2. mongoDB의 자체 config 설정을 찾아 수정한다 => 이 부분은 제가 아직 시도해보지 않았습니다.

혹시 더 찾아보신 자료나, 좋은 방법이 있으시면 말씀해주시면 감사하겠습니다.

**Comment by uni2u** [comment]
참고해서 보겠습니다.

DIFS 에서 ndnputfile 의 의미를 mongoDB 관점으로 볼 때 update 로 봐야 하는지 찾아보고 있습니다. (collection 이 data 로 고정되어 있기 때문에?)
현재는 구글링을 통해 이런저런 내용만 보는 중 입니다.

**Comment by taewoong0627** [comment]
**MongoDB 속도 저하 관련**

MongoDB 쪽 자료를 조사하며 여러가지 방법을 시도해보았지만, 큰 속도 개선이 보이지않아서 코드를 확인하던중에 오류를 발견하였습니다. 기존에는 데이터를 put하면 해당 data_name으로 라우터를 등록하였는데 이전에 '/'으로 통일을 하면서 발생한 문제입니다. '/'으로 수정하면서 segmentFetcher의 요청이 '/' 라우터로 다 전달이 되어 read함수를 호출하여 속도가 느려진것으로 확인되었습니다. 

문제를 해결하고 난 다음 테스트를 해본결과 fs과 큰 차이가 없는것으로 확인하였습니다.

위에 부분을 해결할 방법은 다시 고민해보아야 할 것 같습니다. 데이터 이름별로 다 route 를 추가하게되면 너무 많이 생겨서 '/' 로 통일하려고 하였는데, mongodb쪽에서 이런 문제가 발생할줄은 몰라서 회의를 진행할 때 다시 확인하여야되는 부분이 될 것 같습니다.

**Comment by uni2u** [comment]
@taewoong0627 감사합니다. 관련 내용을 확인하였습니다. 그럼 '/' 가 아닌 경우에는 속도가 나오는지 확인이 필요하겠네요.

**Comment by uni2u** [comment]
@taewoong0627 감사합니다. 관련 내용을 확인하였습니다. 그럼 '/' 가 아닌 경우에는 속도가 나오는지 확인이 필요하겠네요.

**Comment by taewoong0627** [comment]
**MongoDB 성능 회의 관련 글**

내일 있을 회의에 사용할 자료 및 MongoDB Insert 관련 글입니다.

우선 확인해였던 '/' 가 아닌 경우에도 기존 구현되어있던 Insert 함수는 1GB기준으로 굉장히 오랜 시간이 걸리는 것으로 확인됩니다.

원인은 다음과 같습니다.
1. insert 함수가 아닌 replace_one 함수로 구현이 되어있음 => replace_one 함수의 동작이 매우 느림

위의 함수를 아래와 같이 수정을 한 후 테스트한 결과입니다. (측정 기준 Data Parse 후 실제 insert 하는 시간만 측정 => interest 포함)
1. insert_one
1GB 기준으로 약 21~23초 정도 걸립니다.
2. insert_many
1GB 기준으로 17~20초 정도 걸립니다.

두 함수의 차이점은 다음과 같습니다.
insert_one 함수는 매번 collection에 접근을 하게 되므로, 소요시간이 insert_many 보다 동작이 느립니다.
현재 제가 테스트한 기준으로는 insert_many는 약 300개의 chunk를 쌓은 후 insert를 합니다.
=> 1GB기준 12만개의 chunk, insert_one 사용시 12만번의 collection 접근
=> insert_many 사용시 4000번의 collection 접근

collection 접근의 횟수가 줄어들수록 걸리는 시간이 줄어드는것으로 보입니다. 저장하는 chunk size를 조절하여 추가적인 테스트를 진행해 볼 예정입니다. 이 부분은 내일 회의를 진행할 때 size별 측정 시간을 참고하여 정하면 될 것 같습니다.

**Comment by uni2u** [comment]
> **MongoDB 성능 회의 관련 글**

@taewoong0627 님 감사합니다. ndn-python-repo 가 replace_one 을 사용하기에 참고하면 좋겠다고 했습니다만 그냥 구현만 해 놓은 상태인듯 합니다. ndn-python-repo 의 mongodb 쪽에 bulkinsert 가 적용되어 있기에 더 확인했더니 bulk 메시지의 경우 leveldb 를 사용하는 것으로 볼때 아직 기본 기능쪽의 개발을 우선시 하는 것으로 판단됩니다.

**Comment by taewoong0627** [comment]
bulk_insert 관련하여서는 내용을 많이 찾아보았는데, 전에는 함수구조를 보고 확신이 아닌 추측만 하였지만 여러글을 조사해보니 insert_many 내부적으로 bulk_insert 를 사용하고 있었습니다. 확인하였던 글 중에서는 write, delete, update등 여러가지 작업을 동시에 하는 것이 아니라면 bulk_insert가 아닌 직접 insert_many를 호출하여서 사용하는게 더 낫다고 하는 글도 있었습니다.

**Comment by uni2u** [comment]
bulk_insert 를 반드시 사용하여야 한다는 의견은 아닙니다. ^^
저도 이래저래 찾다가 bulk_insert 를 먼저 찾았기에 bulk_insert || insert_many 는 어떠냐고 제안했던 것입니다.
목적은 DIFS 의 성능 향상이니 당연히 방법은 여러가지 있을 수 있습니다.
그러니 기탄없이 성능을 높일 수 있을 것 같은 의견을 제안해주세요~

**Comment by uni2u** [comment]
- insert_many 를 사용하는 것으로 확인
