### ISSUE TITLE
성능개선 - mongodb collection

### ISSUE THREAD

**Issue by uni2u** [uni2u/difs#52]
## large number of collections

- 참조: [mongodb document - large-number-of-collections](https://docs.mongodb.com/manual/core/data-model-operations/#large-number-of-collections)
- 현재 difs 의 mongodb collection 은 `data` 로 정의되어 있음
- collection 을 `[data_name]` 으로 여러개 생성하여 insert/delete 등의 성능을 높이고자 함
  - `ndnputfile`, `ndndelfile` 성능 향상을 기대함
  - `ndngetKeyInfo`, `ndngetInfo` 에 영향은 없을 것으로 예상함
  - 특히, `ndngetfile` 은 현재로서는 별개의 이슈로 접근하여야 할 것으로 예상함
    - `index` 관련 내용을 적용하거나
    - `ndnputfile` 이 요청하는 데이터 크기가 큰 경우 적절 크기로 나누어 collection 을 생성하고 document 를 적용하거나

**Comment by taewoong0627** [comment]
현재 Get관련하여 성능 개선이 있었습니다. (MongoDB)
기존에 1GB로 테스트를 진행하게되면 timeout, getFile 이 끝나지 않는 문제가 있었습니다.

이 부분을 collection을 나누어 성능을 높혀보려하였지만, manifest 수정 및 여러가지 문제들이 있어 Indexing으로 진행한 결과, 1GB 기준으로 약 45초의 시간이 걸리는것으로 확인하였습니다. (데이터 출력 포함)

실제 getFile에 걸리는 시간은 약 4~5초 정도 걸리고 cout 문으로 가져온 데이터를 출력하는 시간으로 인해 45초가 걸리는것으로 확인하였습니다.
