### ISSUE TITLE
Forwarding Hint 적용

### ISSUE THREAD

**Issue by uni2u** [uni2u/difs#7]
### 문제점

- producer 가 insert 하는 name 과 DIFS 가 저장하는 name 차이 발생
  - producer: /repo/insert/a.com/izone.mp4
  - DIFS: /storage01/contents/a.com/izone.mp4
  - name 이 다르기 때문에 **_2번 sign_** 하는 문제 발생

## 적용 방안

2번 sign 하는 문제 해소를 위하여 Forwarding Hint 을 적용

### insert

- ndnputfile <data_name>
  - <data_name> signature 생성
  - DIFS: data+sign (producer 에서 생성한 signature) 형식으로 저장
  - manifest 생성

### get
- ndngetfile <data_name>
  - manifest 확인
  - interest 생성: data_name; tlv: forwarding hint (ex: /storage01/)

### Schedule 

- ~ 2020.11.13.

**Comment by uni2u** [comment]
- 관련하여 2020.09.10. 오전 10시 온라인 미팅을 통하여 우선 진행하는 것으로 함
  - [회의록](https://github.com/uni2u/difs/blob/master/meet/20200910_mom.md)
    - application 레벨의 hash-chain 구현이 완료됨
      - hash-chain 은 ndn-cxx (difs-cxx) 에 포함될 수 있어야 함
        - 설계를 진행중이기에 Fowrarding chain 을 우선 진행하는 것으로 함

- repo-ng 의 움직임
  - https://gerrit.named-data.net/c/repo-ng/+/4807/
  - UCLA 의 Weijia Yuan 이 필요하다는 의견만 제시하였고 code commit 함
  - 코드 자체의 문제, 코드 스타일 및 command 등의 문제로 인하여 반영되지 않음
  - commit 당사자가 졸업한 상태임을 Lixia Zhang 이 알림 (https://www.lists.cs.ucla.edu/pipermail/nfd-dev/2019-May/003645.html)

**Comment by tribela** [comment]
`forward-hint` 브랜치에 포워딩 힌트를 사용한 코드를 구현하였음.
저장 되는 데이터의 네임은 `/<storage prefix>/<repo-id>/<data name>`이었던 것을 `/<storage prefix>/<data name>`으로 바꾸어 노드간 저장된 파일의 복사가 이루어져도 재사용이 가능해짐.
포워딩 힌트는 `/<storage prefix>/<repo-id>`로 매니페스트에 있는 해당 노드를 찾아가도록 함.

도커 3노드 환경(NFD도 각각 1대씩 3대)에서 정상 동작 확인.

**Comment by uni2u** [comment]
@Kjwon15 수고 많으셨습니다. ACM ICN 이후 확인해보겠습니다. 추석 명절 이후 10월 5일 ~ 8일 사이 hash-chain 관련 회의를 진행할 때 까지 off 입니다. 추석 명절 푹 쉬시기 바랍니다.
