### ISSUE TITLE
중복 data_name insert

### ISSUE THREAD

**Issue by uni2u** [uni2u/difs#8]
### [insert]
- `ndnputfile {repo_name} {data_name} {data}`

#### `-s` 옵션
- 세그먼트 크기를 지정하는 옵션이 없음
  - segment size 는 8K 까지 사용자가 지정함

#### `data_name` 중복 처리
- ndnputfile: 같은 data_name 을 요청하는 경우
  - DIFS 멈춤현상 발생
  - DIFS 에서 data_name 은 유일함

- 해결방안
  - warning 메시지 발생
    - exception: `duplicate data_name`
    - DIFS 시스템이 멈추지 않도록 함

**Comment by tribela** [comment]
`-s` option: fixed in d5ed11ba9678c7f958e34337865e4748e78f59d6
duplicated name: fixed in 9bd62abcce31fca6bca17697e1a0f2f20863f6be
