### ISSUE TITLE
없는 data_name get

### ISSUE THREAD

**Issue by uni2u** [uni2u/difs#9]
### [get]
- `ndngetfile {data_name}`

#### 없는 `data_name` 처리
- ndngetfile: 없는 data_name 을 요청하는 경우
  - 'segmentation fault' 발생
  - DIFS 멈춤현상 발생

- 해결방안
  - warning 메시지 발생
    - exception: `data_name not found`
    - DIFS 시스템이 멈추지 않도록 함

**Comment by tribela** [comment]
Fixed in 98ad5ee7d73526a736cd3a1c413a3bf61400168a
